/* CodeMirror - Minified & Bundled
   Generated on 22-02-2017 with http://codemirror.net/doc/compress.html
   Version: 5.24.2

   CodeMirror Library:
   - codemirror.js
   Modes:
   - css.js
   - htmlembedded.js
   - htmlmixed.js
   - javascript.js
   - xml.js
   Add-ons:
   - dialog.js
   - search.js
   - searchcursor.js
 */

(function(Ea,aa){"object"===typeof exports&&"undefined"!==typeof module?module.exports=aa():"function"===typeof define&&define.amd?define(aa):Ea.CodeMirror=aa()})(this,function(){function Ea(a){return new RegExp("(^|\\s)"+a+"(?:$|\\s)\\s*")}function aa(a){for(var b=a.childNodes.length;0<b;--b)a.removeChild(a.firstChild);return a}function W(a,b){return aa(a).appendChild(b)}function v(a,b,c,d){a=document.createElement(a);c&&(a.className=c);d&&(a.style.cssText=d);if("string"==typeof b)a.appendChild(document.createTextNode(b));
else if(b)for(c=0;c<b.length;++c)a.appendChild(b[c]);return a}function Yb(a,b){3==b.nodeType&&(b=b.parentNode);if(a.contains)return a.contains(b);do if(11==b.nodeType&&(b=b.host),b==a)return!0;while(b=b.parentNode)}function pa(){var a;try{a=document.activeElement}catch(b){a=document.body||null}for(;a&&a.root&&a.root.activeElement;)a=a.root.activeElement;return a}function Va(a,b){var c=a.className;Ea(b).test(c)||(a.className+=(c?" ":"")+b)}function Fc(a,b){for(var c=a.split(" "),d=0;d<c.length;d++)c[d]&&
!Ea(c[d]).test(b)&&(b+=" "+c[d]);return b}function Gc(a){var b=Array.prototype.slice.call(arguments,1);return function(){return a.apply(null,b)}}function Fa(a,b,c){b||(b={});for(var d in a)!a.hasOwnProperty(d)||!1===c&&b.hasOwnProperty(d)||(b[d]=a[d]);return b}function ba(a,b,c,d,e){null==b&&(b=a.search(/[^\s\u00a0]/),-1==b&&(b=a.length));d=d||0;for(e=e||0;;){var f=a.indexOf("\t",d);if(0>f||f>=b)return e+(b-d);e+=f-d;e+=c-e%c;d=f+1}}function K(a,b){for(var c=0;c<a.length;++c)if(a[c]==b)return c;return-1}
function Hc(a,b,c){for(var d=0,e=0;;){var f=a.indexOf("\t",d);-1==f&&(f=a.length);var g=f-d;if(f==a.length||e+g>=b)return d+Math.min(g,b-e);e+=f-d;e+=c-e%c;d=f+1;if(e>=b)return d}}function Ic(a){for(;Zb.length<=a;)Zb.push(B(Zb)+" ");return Zb[a]}function B(a){return a[a.length-1]}function $b(a,b){for(var c=[],d=0;d<a.length;d++)c[d]=b(a[d],d);return c}function Mf(a,b,c){for(var d=0,e=c(b);d<a.length&&c(a[d])<=e;)d++;a.splice(d,0,b)}function Ld(){}function Md(a,b){var c;Object.create?c=Object.create(a):
(Ld.prototype=a,c=new Ld);b&&Fa(b,c);return c}function Jc(a){return/\w/.test(a)||"\u0080"<a&&(a.toUpperCase()!=a.toLowerCase()||Nf.test(a))}function ac(a,b){return b?-1<b.source.indexOf("\\w")&&Jc(a)?!0:b.test(a):Jc(a)}function Nd(a){for(var b in a)if(a.hasOwnProperty(b)&&a[b])return!1;return!0}function Kc(a){return 768<=a.charCodeAt(0)&&Of.test(a)}function Od(a,b,c){for(;(0>c?0<b:b<a.length)&&Kc(a.charAt(b));)b+=c;return b}function bc(a,b,c){for(;;){if(1>=Math.abs(b-c))return a(b)?b:c;var d=Math.floor((b+
c)/2);a(d)?c=d:b=d}}function Pf(a,b,c){this.input=c;this.scrollbarFiller=v("div",null,"CodeMirror-scrollbar-filler");this.scrollbarFiller.setAttribute("cm-not-content","true");this.gutterFiller=v("div",null,"CodeMirror-gutter-filler");this.gutterFiller.setAttribute("cm-not-content","true");this.lineDiv=v("div",null,"CodeMirror-code");this.selectionDiv=v("div",null,null,"position: relative; z-index: 1");this.cursorDiv=v("div",null,"CodeMirror-cursors");this.measure=v("div",null,"CodeMirror-measure");
this.lineMeasure=v("div",null,"CodeMirror-measure");this.lineSpace=v("div",[this.measure,this.lineMeasure,this.selectionDiv,this.cursorDiv,this.lineDiv],null,"position: relative; outline: none");this.mover=v("div",[v("div",[this.lineSpace],"CodeMirror-lines")],null,"position: relative");this.sizer=v("div",[this.mover],"CodeMirror-sizer");this.sizerWidth=null;this.heightForcer=v("div",null,null,"position: absolute; height: 30px; width: 1px;");this.gutters=v("div",null,"CodeMirror-gutters");this.lineGutter=
null;this.scroller=v("div",[this.sizer,this.heightForcer,this.gutters],"CodeMirror-scroll");this.scroller.setAttribute("tabIndex","-1");this.wrapper=v("div",[this.scrollbarFiller,this.gutterFiller,this.scroller],"CodeMirror");C&&8>z&&(this.gutters.style.zIndex=-1,this.scroller.style.paddingRight=0);L||wa&&sb||(this.scroller.draggable=!0);a&&(a.appendChild?a.appendChild(this.wrapper):a(this.wrapper));this.reportedViewFrom=this.reportedViewTo=this.viewFrom=this.viewTo=b.first;this.view=[];this.externalMeasured=
this.renderedView=null;this.lastWrapHeight=this.lastWrapWidth=this.viewOffset=0;this.updateLineNumbers=null;this.nativeBarWidth=this.barHeight=this.barWidth=0;this.scrollbarsClipped=!1;this.lineNumWidth=this.lineNumInnerWidth=this.lineNumChars=null;this.alignWidgets=!1;this.maxLine=this.cachedCharWidth=this.cachedTextHeight=this.cachedPaddingH=null;this.maxLineLength=0;this.maxLineChanged=!1;this.wheelDX=this.wheelDY=this.wheelStartX=this.wheelStartY=null;this.shift=!1;this.activeTouch=this.selForContextMenu=
null;c.init(this)}function r(a,b){b-=a.first;if(0>b||b>=a.size)throw Error("There is no line "+(b+a.first)+" in the document.");for(var c=a;!c.lines;)for(var d=0;;++d){var e=c.children[d],f=e.chunkSize();if(b<f){c=e;break}b-=f}return c.lines[b]}function Ga(a,b,c){var d=[],e=b.line;a.iter(b.line,c.line+1,function(a){a=a.text;e==c.line&&(a=a.slice(0,c.ch));e==b.line&&(a=a.slice(b.ch));d.push(a);++e});return d}function Lc(a,b,c){var d=[];a.iter(b,c,function(a){d.push(a.text)});return d}function ia(a,
b){var c=b-a.height;if(c)for(var d=a;d;d=d.parent)d.height+=c}function D(a){if(null==a.parent)return null;var b=a.parent;a=K(b.lines,a);for(var c=b.parent;c;b=c,c=c.parent)for(var d=0;c.children[d]!=b;++d)a+=c.children[d].chunkSize();return a+b.first}function Ha(a,b){var c=a.first;a:do{for(var d=0;d<a.children.length;++d){var e=a.children[d],f=e.height;if(b<f){a=e;continue a}b-=f;c+=e.chunkSize()}return c}while(!a.lines);for(d=0;d<a.lines.length;++d){e=a.lines[d].height;if(b<e)break;b-=e}return c+
d}function tb(a,b){return b>=a.first&&b<a.first+a.size}function Mc(a,b){return String(a.lineNumberFormatter(b+a.firstLineNumber))}function q(a,b,c){void 0===c&&(c=null);if(!(this instanceof q))return new q(a,b,c);this.line=a;this.ch=b;this.sticky=c}function x(a,b){return a.line-b.line||a.ch-b.ch}function Nc(a,b){return a.sticky==b.sticky&&0==x(a,b)}function Oc(a){return q(a.line,a.ch)}function cc(a,b){return 0>x(a,b)?b:a}function dc(a,b){return 0>x(a,b)?a:b}function t(a,b){if(b.line<a.first)return q(a.first,
0);var c=a.first+a.size-1;if(b.line>c)return q(c,r(a,c).text.length);var c=r(a,b.line).text.length,d=b.ch,c=null==d||d>c?q(b.line,c):0>d?q(b.line,0):b;return c}function Pd(a,b){for(var c=[],d=0;d<b.length;d++)c[d]=t(a,b[d]);return c}function ec(a,b,c){this.marker=a;this.from=b;this.to=c}function ub(a,b){if(a)for(var c=0;c<a.length;++c){var d=a[c];if(d.marker==b)return d}}function Pc(a,b){if(b.full)return null;var c=tb(a,b.from.line)&&r(a,b.from.line).markedSpans,d=tb(a,b.to.line)&&r(a,b.to.line).markedSpans;
if(!c&&!d)return null;var e=b.from.ch,f=b.to.ch,g=0==x(b.from,b.to),h;if(c)for(var k=0;k<c.length;++k){var l=c[k],m=l.marker;if(null==l.from||(m.inclusiveLeft?l.from<=e:l.from<e)||!(l.from!=e||"bookmark"!=m.type||g&&l.marker.insertLeft)){var n=null==l.to||(m.inclusiveRight?l.to>=e:l.to>e);(h||(h=[])).push(new ec(m,l.from,n?null:l.to))}}var c=h,p;if(d)for(h=0;h<d.length;++h)if(k=d[h],l=k.marker,null==k.to||(l.inclusiveRight?k.to>=f:k.to>f)||k.from==f&&"bookmark"==l.type&&(!g||k.marker.insertLeft))m=
null==k.from||(l.inclusiveLeft?k.from<=f:k.from<f),(p||(p=[])).push(new ec(l,m?null:k.from-f,null==k.to?null:k.to-f));d=p;f=1==b.text.length;g=B(b.text).length+(f?e:0);if(c)for(p=0;p<c.length;++p)if(h=c[p],null==h.to)(k=ub(d,h.marker),k)?f&&(h.to=null==k.to?null:k.to+g):h.to=e;if(d)for(e=0;e<d.length;++e)p=d[e],null!=p.to&&(p.to+=g),null==p.from?ub(c,p.marker)||(p.from=g,f&&(c||(c=[])).push(p)):(p.from+=g,f&&(c||(c=[])).push(p));c&&(c=Qd(c));d&&d!=c&&(d=Qd(d));e=[c];if(!f){var f=b.text.length-2,u;
if(0<f&&c)for(g=0;g<c.length;++g)null==c[g].to&&(u||(u=[])).push(new ec(c[g].marker,null,null));for(c=0;c<f;++c)e.push(u);e.push(d)}return e}function Qd(a){for(var b=0;b<a.length;++b){var c=a[b];null!=c.from&&c.from==c.to&&!1!==c.marker.clearWhenEmpty&&a.splice(b--,1)}return a.length?a:null}function Qf(a,b,c){var d=null;a.iter(b.line,c.line+1,function(a){if(a.markedSpans)for(var b=0;b<a.markedSpans.length;++b){var c=a.markedSpans[b].marker;!c.readOnly||d&&-1!=K(d,c)||(d||(d=[])).push(c)}});if(!d)return null;
a=[{from:b,to:c}];for(b=0;b<d.length;++b){c=d[b];for(var e=c.find(0),f=0;f<a.length;++f){var g=a[f];if(!(0>x(g.to,e.from)||0<x(g.from,e.to))){var h=[f,1],k=x(g.from,e.from),l=x(g.to,e.to);(0>k||!c.inclusiveLeft&&!k)&&h.push({from:g.from,to:e.from});(0<l||!c.inclusiveRight&&!l)&&h.push({from:e.to,to:g.to});a.splice.apply(a,h);f+=h.length-3}}}return a}function Rd(a){var b=a.markedSpans;if(b){for(var c=0;c<b.length;++c)b[c].marker.detachLine(a);a.markedSpans=null}}function Sd(a,b){if(b){for(var c=0;c<
b.length;++c)b[c].marker.attachLine(a);a.markedSpans=b}}function Td(a,b){var c=a.lines.length-b.lines.length;if(0!=c)return c;var c=a.find(),d=b.find(),e=x(c.from,d.from)||(a.inclusiveLeft?-1:0)-(b.inclusiveLeft?-1:0);return e?-e:(c=x(c.to,d.to)||(a.inclusiveRight?1:0)-(b.inclusiveRight?1:0))?c:b.id-a.id}function Ia(a,b){var c=xa&&a.markedSpans,d;if(c)for(var e,f=0;f<c.length;++f)e=c[f],e.marker.collapsed&&null==(b?e.from:e.to)&&(!d||0>Td(d,e.marker))&&(d=e.marker);return d}function Ud(a,b,c,d,e){a=
r(a,b);if(a=xa&&a.markedSpans)for(b=0;b<a.length;++b){var f=a[b];if(f.marker.collapsed){var g=f.marker.find(0),h=x(g.from,c)||(f.marker.inclusiveLeft?-1:0)-(e.inclusiveLeft?-1:0),k=x(g.to,d)||(f.marker.inclusiveRight?1:0)-(e.inclusiveRight?1:0);if(!(0<=h&&0>=k||0>=h&&0<=k)&&(0>=h&&(f.marker.inclusiveRight&&e.inclusiveLeft?0<=x(g.to,c):0<x(g.to,c))||0<=h&&(f.marker.inclusiveRight&&e.inclusiveLeft?0>=x(g.from,d):0>x(g.from,d))))return!0}}}function ja(a){for(var b;b=Ia(a,!0);)a=b.find(-1,!0).line;return a}
function Qc(a,b){var c=r(a,b),d=ja(c);return c==d?b:D(d)}function Vd(a,b){if(b>a.lastLine())return b;var c=r(a,b),d;if(!Ja(a,c))return b;for(;d=Ia(c,!1);)c=d.find(1,!0).line;return D(c)+1}function Ja(a,b){var c=xa&&b.markedSpans;if(c)for(var d,e=0;e<c.length;++e)if(d=c[e],d.marker.collapsed&&(null==d.from||!d.marker.widgetNode&&0==d.from&&d.marker.inclusiveLeft&&Rc(a,b,d)))return!0}function Rc(a,b,c){if(null==c.to)return b=c.marker.find(1,!0),Rc(a,b.line,ub(b.line.markedSpans,c.marker));if(c.marker.inclusiveRight&&
c.to==b.text.length)return!0;for(var d,e=0;e<b.markedSpans.length;++e)if(d=b.markedSpans[e],d.marker.collapsed&&!d.marker.widgetNode&&d.from==c.to&&(null==d.to||d.to!=c.from)&&(d.marker.inclusiveLeft||c.marker.inclusiveRight)&&Rc(a,b,d))return!0}function ka(a){a=ja(a);for(var b=0,c=a.parent,d=0;d<c.lines.length;++d){var e=c.lines[d];if(e==a)break;else b+=e.height}for(a=c.parent;a;c=a,a=c.parent)for(d=0;d<a.children.length&&(e=a.children[d],e!=c);++d)b+=e.height;return b}function fc(a){if(0==a.height)return 0;
for(var b=a.text.length,c,d=a;c=Ia(d,!0);)c=c.find(0,!0),d=c.from.line,b+=c.from.ch-c.to.ch;for(d=a;c=Ia(d,!1);)a=c.find(0,!0),b-=d.text.length-a.from.ch,d=a.to.line,b+=d.text.length-a.to.ch;return b}function Sc(a){var b=a.display;a=a.doc;b.maxLine=r(a,a.first);b.maxLineLength=fc(b.maxLine);b.maxLineChanged=!0;a.iter(function(a){var d=fc(a);d>b.maxLineLength&&(b.maxLineLength=d,b.maxLine=a)})}function Rf(a,b,c,d){if(!a)return d(b,c,"ltr");for(var e=!1,f=0;f<a.length;++f){var g=a[f];if(g.from<c&&g.to>
b||b==c&&g.to==b)d(Math.max(g.from,b),Math.min(g.to,c),1==g.level?"rtl":"ltr"),e=!0}e||d(b,c,"ltr")}function Tc(a,b,c){var d;vb=null;for(var e=0;e<a.length;++e){var f=a[e];if(f.from<b&&f.to>b)return e;f.to==b&&(f.from!=f.to&&"before"==c?d=e:vb=e);f.from==b&&(f.from!=f.to&&"before"!=c?d=e:vb=e)}return null!=d?d:vb}function ya(a){var b=a.order;null==b&&(b=a.order=Sf(a.text));return b}function Uc(a,b,c){b=Od(a.text,b+c,c);return 0>b||b>a.text.length?null:b}function Vc(a,b,c){a=Uc(a,b.ch,c);return null==
a?null:new q(b.line,a,0>c?"after":"before")}function Wc(a,b,c,d,e){if(a&&(a=ya(c))){a=0>e?B(a):a[0];var f=0>e==(1==a.level)?"after":"before",g;if(0<a.level){var h=Wa(b,c);g=0>e?c.text.length-1:0;var k=qa(b,h,g).top;g=bc(function(a){return qa(b,h,a).top==k},0>e==(1==a.level)?a.from:a.to-1,g);"before"==f&&(g=Uc(c,g,1,!0))}else g=0>e?a.to:a.from;return new q(d,g,f)}return new q(d,0>e?c.text.length:0,0>e?"before":"after")}function Wd(a,b,c,d){var e=ya(b);if(!e)return Vc(b,c,d);c.ch>=b.text.length?(c.ch=
b.text.length,c.sticky="before"):0>=c.ch&&(c.ch=0,c.sticky="after");var f=Tc(e,c.ch,c.sticky),g=e[f];if(0==g.level%2&&(0<d?g.to>c.ch:g.from<c.ch))return Vc(b,c,d);var h=function(a,d){return Uc(b,a instanceof q?a.ch:a,d)},k,l=function(d){if(!a.options.lineWrapping)return{begin:0,end:b.text.length};var c=k=k||Wa(a,b);d=Ka(a,b,qa(a,c,d),"line").top;return Xd(a,b,c,d)},m=l("before"==c.sticky?h(c,-1):c.ch);if(1==g.level%2){var n=h(c,-d);if(null!=n&&(0<d?n>=g.from&&n>=m.begin:n<=g.to&&n<=m.end))return new q(c.line,
n,0>d?"before":"after")}g=function(a,b,d){for(var f=function(a,b){return b?new q(c.line,h(a,1),"before"):new q(c.line,a,"after")};0<=a&&a<e.length;a+=b){var g=e[a],k=0<b==(1!=g.level),l=k?d.begin:h(d.end,-1);if(g.from<=l&&l<g.to)return f(l,k);l=k?g.from:h(g.to,-1);if(d.begin<=l&&l<d.end)return f(l,k)}};if(f=g(f+d,d,m))return f;m=0<d?m.end:h(m.begin,-1);return null==m||0<d&&m==b.text.length||!(f=g(0<d?0:e.length-1,d,l(m)))?null:f}function da(a,b,c){if(a.removeEventListener)a.removeEventListener(b,
c,!1);else if(a.detachEvent)a.detachEvent("on"+b,c);else{var d=(a=a._handlers)&&a[b];d&&(c=K(d,c),-1<c&&(a[b]=d.slice(0,c).concat(d.slice(c+1))))}}function F(a,b){var c=a._handlers&&a._handlers[b]||gc;if(c.length)for(var d=Array.prototype.slice.call(arguments,2),e=0;e<c.length;++e)c[e].apply(null,d)}function H(a,b,c){"string"==typeof b&&(b={type:b,preventDefault:function(){this.defaultPrevented=!0}});F(a,c||b.type,a,b);return Xc(b)||b.codemirrorIgnore}function Yd(a){var b=a._handlers&&a._handlers.cursorActivity;
if(b){a=a.curOp.cursorActivityHandlers||(a.curOp.cursorActivityHandlers=[]);for(var c=0;c<b.length;++c)-1==K(a,b[c])&&a.push(b[c])}}function ca(a,b){return 0<(a._handlers&&a._handlers[b]||gc).length}function Xa(a){a.prototype.on=function(a,c){w(this,a,c)};a.prototype.off=function(a,c){da(this,a,c)}}function P(a){a.preventDefault?a.preventDefault():a.returnValue=!1}function Zd(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function Xc(a){return null!=a.defaultPrevented?a.defaultPrevented:
0==a.returnValue}function wb(a){P(a);Zd(a)}function $d(a){var b=a.which;null==b&&(a.button&1?b=1:a.button&2?b=3:a.button&4&&(b=2));ea&&a.ctrlKey&&1==b&&(b=3);return b}function Tf(a){if(null==Yc){var b=v("span","\u200b");W(a,v("span",[b,document.createTextNode("x")]));0!=a.firstChild.offsetHeight&&(Yc=1>=b.offsetWidth&&2<b.offsetHeight&&!(C&&8>z))}a=Yc?v("span","\u200b"):v("span","\u00a0",null,"display: inline-block; width: 1px; margin-right: -1px");a.setAttribute("cm-text","");return a}function Uf(a,
b){2<arguments.length&&(b.dependencies=Array.prototype.slice.call(arguments,2));Zc[a]=b}function hc(a){if("string"==typeof a&&Ya.hasOwnProperty(a))a=Ya[a];else if(a&&"string"==typeof a.name&&Ya.hasOwnProperty(a.name)){var b=Ya[a.name];"string"==typeof b&&(b={name:b});a=Md(b,a);a.name=b.name}else{if("string"==typeof a&&/^[\w\-]+\/[\w\-]+\+xml$/.test(a))return hc("application/xml");if("string"==typeof a&&/^[\w\-]+\/[\w\-]+\+json$/.test(a))return hc("application/json")}return"string"==typeof a?{name:a}:
a||{name:"null"}}function $c(a,b){b=hc(b);var c=Zc[b.name];if(!c)return $c(a,"text/plain");c=c(a,b);if(Za.hasOwnProperty(b.name)){var d=Za[b.name],e;for(e in d)d.hasOwnProperty(e)&&(c.hasOwnProperty(e)&&(c["_"+e]=c[e]),c[e]=d[e])}c.name=b.name;b.helperType&&(c.helperType=b.helperType);if(b.modeProps)for(var f in b.modeProps)c[f]=b.modeProps[f];return c}function Vf(a,b){var c=Za.hasOwnProperty(a)?Za[a]:Za[a]={};Fa(b,c)}function ra(a,b){if(!0===b)return b;if(a.copyState)return a.copyState(b);var c=
{},d;for(d in b){var e=b[d];e instanceof Array&&(e=e.concat([]));c[d]=e}return c}function ad(a,b){for(var c;a.innerMode;){c=a.innerMode(b);if(!c||c.mode==a)break;b=c.state;a=c.mode}return c||{mode:a,state:b}}function ae(a,b,c){return a.startState?a.startState(b,c):!0}function be(a,b,c,d){var e=[a.state.modeGen],f={};ce(a,b.text,a.doc.mode,c,function(a,b){return e.push(a,b)},f,d);c=function(d){var c=a.state.overlays[d],g=1,l=0;ce(a,b.text,c.mode,!0,function(a,b){for(var d=g;l<a;){var f=e[g];f>a&&e.splice(g,
1,a,e[g+1],f);g+=2;l=Math.min(a,f)}if(b)if(c.opaque)e.splice(d,g-d,a,"overlay "+b),g=d+2;else for(;d<g;d+=2)f=e[d+1],e[d+1]=(f?f+" ":"")+"overlay "+b},f)};for(d=0;d<a.state.overlays.length;++d)c(d);return{styles:e,classes:f.bgClass||f.textClass?f:null}}function de(a,b,c){if(!b.styles||b.styles[0]!=a.state.modeGen){var d=xb(a,D(b)),e=be(a,b,b.text.length>a.options.maxHighlightLength?ra(a.doc.mode,d):d);b.stateAfter=d;b.styles=e.styles;e.classes?b.styleClasses=e.classes:b.styleClasses&&(b.styleClasses=
null);c===a.doc.frontier&&a.doc.frontier++}return b.styles}function xb(a,b,c){var d=a.doc,e=a.display;if(!d.mode.startState)return!0;var f=Wf(a,b,c),g=f>d.first&&r(d,f-1).stateAfter,g=g?ra(d.mode,g):ae(d.mode);d.iter(f,b,function(c){bd(a,c.text,g);c.stateAfter=f==b-1||0==f%5||f>=e.viewFrom&&f<e.viewTo?ra(d.mode,g):null;++f});c&&(d.frontier=f);return g}function bd(a,b,c,d){var e=a.doc.mode;a=new I(b,a.options.tabSize);a.start=a.pos=d||0;for(""==b&&ee(e,c);!a.eol();)cd(e,a,c),a.start=a.pos}function ee(a,
b){if(a.blankLine)return a.blankLine(b);if(a.innerMode){var c=ad(a,b);if(c.mode.blankLine)return c.mode.blankLine(c.state)}}function cd(a,b,c,d){for(var e=0;10>e;e++){d&&(d[0]=ad(a,c).mode);var f=a.token(b,c);if(b.pos>b.start)return f}throw Error("Mode "+a.name+" failed to advance stream.");}function fe(a,b,c,d){var e=function(a){return{start:m.start,end:m.pos,string:m.current(),type:h||null,state:a?ra(f.mode,l):l}},f=a.doc,g=f.mode,h;b=t(f,b);var k=r(f,b.line),l=xb(a,b.line,c),m=new I(k.text,a.options.tabSize),
n;for(d&&(n=[]);(d||m.pos<b.ch)&&!m.eol();)m.start=m.pos,h=cd(g,m,l),d&&n.push(e(!0));return d?n:e()}function ge(a,b){if(a)for(;;){var c=a.match(/(?:^|\s+)line-(background-)?(\S+)/);if(!c)break;a=a.slice(0,c.index)+a.slice(c.index+c[0].length);var d=c[1]?"bgClass":"textClass";null==b[d]?b[d]=c[2]:(new RegExp("(?:^|s)"+c[2]+"(?:$|s)")).test(b[d])||(b[d]+=" "+c[2])}return a}function ce(a,b,c,d,e,f,g){var h=c.flattenSpans;null==h&&(h=a.options.flattenSpans);var k=0,l=null,m=new I(b,a.options.tabSize),
n,p=a.options.addModeClass&&[null];for(""==b&&ge(ee(c,d),f);!m.eol();){m.pos>a.options.maxHighlightLength?(h=!1,g&&bd(a,b,d,m.pos),m.pos=b.length,n=null):n=ge(cd(c,m,d,p),f);if(p){var u=p[0].name;u&&(n="m-"+(n?u+" "+n:u))}if(!h||l!=n){for(;k<m.start;)k=Math.min(m.start,k+5E3),e(k,l);l=n}m.start=m.pos}for(;k<m.pos;)a=Math.min(m.pos,k+5E3),e(a,l),k=a}function Wf(a,b,c){for(var d,e,f=a.doc,g=c?-1:b-(a.doc.mode.innerMode?1E3:100);b>g;--b){if(b<=f.first)return f.first;var h=r(f,b-1);if(h.stateAfter&&(!c||
b<=f.frontier))return b;h=ba(h.text,null,a.options.tabSize);if(null==e||d>h)e=b-1,d=h}return e}function he(a,b){if(!a||/^\s*$/.test(a))return null;var c=b.addModeClass?Xf:Yf;return c[a]||(c[a]=a.replace(/\S+/g,"cm-$&"))}function ie(a,b){var c=v("span",null,null,L?"padding-right: .1px":null),d={pre:v("pre",[c],"CodeMirror-line"),content:c,col:0,pos:0,cm:a,trailingSpace:!1,splitSpaces:(C||L)&&a.getOption("lineWrapping")};c.setAttribute("role","presentation");d.pre.setAttribute("role","presentation");
b.measure={};for(c=0;c<=(b.rest?b.rest.length:0);c++){var e=c?b.rest[c-1]:b.line,f=void 0;d.pos=0;d.addToken=Zf;var g;g=a.display.measure;if(null!=dd)g=dd;else{var h=W(g,document.createTextNode("A\u062eA")),k=$a(h,0,1).getBoundingClientRect(),h=$a(h,1,2).getBoundingClientRect();aa(g);g=k&&k.left!=k.right?dd=3>h.right-k.right:!1}g&&(f=ya(e))&&(d.addToken=$f(d.addToken,f));d.map=[];var l=b!=a.display.externalMeasured&&D(e);a:{var m=h=k=g=void 0,n=void 0,p=void 0,u=void 0,f=d,l=de(a,e,l),q=e.markedSpans,
r=e.text,w=0;if(q)for(var x=r.length,t=0,B=1,La="",la=0;;){if(la==t){n=m=h=k=p="";g=null;for(var la=Infinity,sa=[],V=void 0,A=0;A<q.length;++A){var y=q[A],z=y.marker;"bookmark"==z.type&&y.from==t&&z.widgetNode?sa.push(z):y.from<=t&&(null==y.to||y.to>t||z.collapsed&&y.to==t&&y.from==t)?(null!=y.to&&y.to!=t&&la>y.to&&(la=y.to,m=""),z.className&&(n+=" "+z.className),z.css&&(p=(p?p+";":"")+z.css),z.startStyle&&y.from==t&&(h+=" "+z.startStyle),z.endStyle&&y.to==la&&(V||(V=[])).push(z.endStyle,y.to),z.title&&
!k&&(k=z.title),z.collapsed&&(!g||0>Td(g.marker,z))&&(g=y)):y.from>t&&la>y.from&&(la=y.from)}if(V)for(A=0;A<V.length;A+=2)V[A+1]==la&&(m+=" "+V[A]);if(!g||g.from==t)for(V=0;V<sa.length;++V)je(f,0,sa[V]);if(g&&(g.from||0)==t){je(f,(null==g.to?x+1:g.to)-t,g.marker,null==g.from);if(null==g.to)break a;g.to==t&&(g=!1)}}if(t>=x)break;for(sa=Math.min(x,la);;){if(La){V=t+La.length;g||(A=V>sa?La.slice(0,sa-t):La,f.addToken(f,A,u?u+n:n,h,t+A.length==la?m:"",k,p));if(V>=sa){La=La.slice(sa-t);t=sa;break}t=V;
h=""}La=r.slice(w,w=l[B++]);u=he(l[B++],f.cm.options)}}else for(g=1;g<l.length;g+=2)f.addToken(f,r.slice(w,w=l[g]),he(l[g+1],f.cm.options))}e.styleClasses&&(e.styleClasses.bgClass&&(d.bgClass=Fc(e.styleClasses.bgClass,d.bgClass||"")),e.styleClasses.textClass&&(d.textClass=Fc(e.styleClasses.textClass,d.textClass||"")));0==d.map.length&&d.map.push(0,0,d.content.appendChild(Tf(a.display.measure)));0==c?(b.measure.map=d.map,b.measure.cache={}):((b.measure.maps||(b.measure.maps=[])).push(d.map),(b.measure.caches||
(b.measure.caches=[])).push({}))}L&&(c=d.content.lastChild,/\bcm-tab\b/.test(c.className)||c.querySelector&&c.querySelector(".cm-tab"))&&(d.content.className="cm-tab-wrap-hack");F(a,"renderLine",a,b.line,d.pre);d.pre.className&&(d.textClass=Fc(d.pre.className,d.textClass||""));return d}function ag(a){var b=v("span","\u2022","cm-invalidchar");b.title="\\u"+a.charCodeAt(0).toString(16);b.setAttribute("aria-label",b.title);return b}function Zf(a,b,c,d,e,f,g){if(b){var h;if(a.splitSpaces)if(h=a.trailingSpace,
1<b.length&&!/  /.test(b))h=b;else{for(var k="",l=0;l<b.length;l++){var m=b.charAt(l);" "!=m||!h||l!=b.length-1&&32!=b.charCodeAt(l+1)||(m="\u00a0");k+=m;h=" "==m}h=k}else h=b;k=h;l=a.cm.state.specialChars;m=!1;if(l.test(b)){h=document.createDocumentFragment();for(var n=0;;){l.lastIndex=n;var p=l.exec(b),u=p?p.index-n:b.length-n;if(u){var q=document.createTextNode(k.slice(n,n+u));C&&9>z?h.appendChild(v("span",[q])):h.appendChild(q);a.map.push(a.pos,a.pos+u,q);a.col+=u;a.pos+=u}if(!p)break;n+=u+1;
"\t"==p[0]?(p=a.cm.options.tabSize,p-=a.col%p,u=h.appendChild(v("span",Ic(p),"cm-tab")),u.setAttribute("role","presentation"),u.setAttribute("cm-text","\t"),a.col+=p):("\r"==p[0]||"\n"==p[0]?(u=h.appendChild(v("span","\r"==p[0]?"\u240d":"\u2424","cm-invalidchar")),u.setAttribute("cm-text",p[0])):(u=a.cm.options.specialCharPlaceholder(p[0]),u.setAttribute("cm-text",p[0]),C&&9>z?h.appendChild(v("span",[u])):h.appendChild(u)),a.col+=1);a.map.push(a.pos,a.pos+1,u);a.pos++}}else a.col+=b.length,h=document.createTextNode(k),
a.map.push(a.pos,a.pos+b.length,h),C&&9>z&&(m=!0),a.pos+=b.length;a.trailingSpace=32==k.charCodeAt(b.length-1);if(c||d||e||m||g)return b=c||"",d&&(b+=d),e&&(b+=e),d=v("span",[h],b,g),f&&(d.title=f),a.content.appendChild(d);a.content.appendChild(h)}}function $f(a,b){return function(c,d,e,f,g,h,k){e=e?e+" cm-force-border":"cm-force-border";for(var l=c.pos,m=l+d.length;;){for(var n=void 0,p=0;p<b.length&&!(n=b[p],n.to>l&&n.from<=l);p++);if(n.to>=m)return a(c,d,e,f,g,h,k);a(c,d.slice(0,n.to-l),e,f,null,
h,k);f=null;d=d.slice(n.to-l);l=n.to}}}function je(a,b,c,d){var e=!d&&c.widgetNode;e&&a.map.push(a.pos,a.pos+b,e);!d&&a.cm.display.input.needsContentAttribute&&(e||(e=a.content.appendChild(document.createElement("span"))),e.setAttribute("cm-marker",c.id));e&&(a.cm.display.input.setUneditable(e),a.content.appendChild(e));a.pos+=b;a.trailingSpace=!1}function ke(a,b,c){for(var d=this.line=b,e;d=Ia(d,!1);)d=d.find(1,!0).line,(e||(e=[])).push(d);this.size=(this.rest=e)?D(B(this.rest))-c+1:1;this.node=
this.text=null;this.hidden=Ja(a,b)}function ic(a,b,c){var d=[],e;for(e=b;e<c;)b=new ke(a.doc,r(a.doc,e),e),e+=b.size,d.push(b);return d}function bg(a,b){var c=a.ownsGroup;if(c)try{var d=c.delayedCallbacks,e=0;do{for(;e<d.length;e++)d[e].call(null);for(var f=0;f<c.ops.length;f++){var g=c.ops[f];if(g.cursorActivityHandlers)for(;g.cursorActivityCalled<g.cursorActivityHandlers.length;)g.cursorActivityHandlers[g.cursorActivityCalled++].call(null,g.cm)}}while(e<d.length)}finally{ab=null,b(c)}}function M(a,
b){var c=a._handlers&&a._handlers[b]||gc;if(c.length){var d=Array.prototype.slice.call(arguments,2),e;ab?e=ab.delayedCallbacks:yb?e=yb:(e=yb=[],setTimeout(cg,0));for(var f=function(a){e.push(function(){return c[a].apply(null,d)})},g=0;g<c.length;++g)f(g)}}function cg(){var a=yb;yb=null;for(var b=0;b<a.length;++b)a[b]()}function le(a,b,c,d){for(var e=0;e<b.changes.length;e++){var f=b.changes[e];if("text"==f){var f=b,g=f.text.className,h=me(a,f);f.text==f.node&&(f.node=h.pre);f.text.parentNode.replaceChild(h.pre,
f.text);f.text=h.pre;h.bgClass!=f.bgClass||h.textClass!=f.textClass?(f.bgClass=h.bgClass,f.textClass=h.textClass,ed(f)):g&&(f.text.className=g)}else if("gutter"==f)ne(a,b,c,d);else if("class"==f)ed(b);else if("widget"==f){f=a;g=b;h=d;g.alignable&&(g.alignable=null);for(var k=g.node.firstChild,l;k;k=l)l=k.nextSibling,"CodeMirror-linewidget"==k.className&&g.node.removeChild(k);oe(f,g,h)}}b.changes=null}function zb(a){a.node==a.text&&(a.node=v("div",null,null,"position: relative"),a.text.parentNode&&
a.text.parentNode.replaceChild(a.node,a.text),a.node.appendChild(a.text),C&&8>z&&(a.node.style.zIndex=2));return a.node}function me(a,b){var c=a.display.externalMeasured;return c&&c.line==b.line?(a.display.externalMeasured=null,b.measure=c.measure,c.built):ie(a,b)}function ed(a){var b=a.bgClass?a.bgClass+" "+(a.line.bgClass||""):a.line.bgClass;b&&(b+=" CodeMirror-linebackground");if(a.background)b?a.background.className=b:(a.background.parentNode.removeChild(a.background),a.background=null);else if(b){var c=
zb(a);a.background=c.insertBefore(v("div",null,b),c.firstChild)}a.line.wrapClass?zb(a).className=a.line.wrapClass:a.node!=a.text&&(a.node.className="");a.text.className=(a.textClass?a.textClass+" "+(a.line.textClass||""):a.line.textClass)||""}function ne(a,b,c,d){b.gutter&&(b.node.removeChild(b.gutter),b.gutter=null);b.gutterBackground&&(b.node.removeChild(b.gutterBackground),b.gutterBackground=null);if(b.line.gutterClass){var e=zb(b);b.gutterBackground=v("div",null,"CodeMirror-gutter-background "+
b.line.gutterClass,"left: "+(a.options.fixedGutter?d.fixedPos:-d.gutterTotalWidth)+"px; width: "+d.gutterTotalWidth+"px");e.insertBefore(b.gutterBackground,b.text)}e=b.line.gutterMarkers;if(a.options.lineNumbers||e){var f=zb(b),g=b.gutter=v("div",null,"CodeMirror-gutter-wrapper","left: "+(a.options.fixedGutter?d.fixedPos:-d.gutterTotalWidth)+"px");a.display.input.setUneditable(g);f.insertBefore(g,b.text);b.line.gutterClass&&(g.className+=" "+b.line.gutterClass);!a.options.lineNumbers||e&&e["CodeMirror-linenumbers"]||
(b.lineNumber=g.appendChild(v("div",Mc(a.options,c),"CodeMirror-linenumber CodeMirror-gutter-elt","left: "+d.gutterLeft["CodeMirror-linenumbers"]+"px; width: "+a.display.lineNumInnerWidth+"px")));if(e)for(b=0;b<a.options.gutters.length;++b)c=a.options.gutters[b],(f=e.hasOwnProperty(c)&&e[c])&&g.appendChild(v("div",[f],"CodeMirror-gutter-elt","left: "+d.gutterLeft[c]+"px; width: "+d.gutterWidth[c]+"px"))}}function dg(a,b,c,d){var e=me(a,b);b.text=b.node=e.pre;e.bgClass&&(b.bgClass=e.bgClass);e.textClass&&
(b.textClass=e.textClass);ed(b);ne(a,b,c,d);oe(a,b,d);return b.node}function oe(a,b,c){pe(a,b.line,b,c,!0);if(b.rest)for(var d=0;d<b.rest.length;d++)pe(a,b.rest[d],b,c,!1)}function pe(a,b,c,d,e){if(b.widgets){var f=zb(c),g=0;for(b=b.widgets;g<b.length;++g){var h=b[g],k=v("div",[h.node],"CodeMirror-linewidget");h.handleMouseEvents||k.setAttribute("cm-ignore-events","true");var l=h,m=k,n=d;if(l.noHScroll){(c.alignable||(c.alignable=[])).push(m);var p=n.wrapperWidth;m.style.left=n.fixedPos+"px";l.coverGutter||
(p-=n.gutterTotalWidth,m.style.paddingLeft=n.gutterTotalWidth+"px");m.style.width=p+"px"}l.coverGutter&&(m.style.zIndex=5,m.style.position="relative",l.noHScroll||(m.style.marginLeft=-n.gutterTotalWidth+"px"));a.display.input.setUneditable(k);e&&h.above?f.insertBefore(k,c.gutter||c.text):f.appendChild(k);M(h,"redraw")}}}function Ab(a){if(null!=a.height)return a.height;var b=a.doc.cm;if(!b)return 0;if(!Yb(document.body,a.node)){var c="position: relative;";a.coverGutter&&(c+="margin-left: -"+b.display.gutters.offsetWidth+
"px;");a.noHScroll&&(c+="width: "+b.display.wrapper.clientWidth+"px;");W(b.display.measure,v("div",[a.node],null,c))}return a.height=a.node.parentNode.offsetHeight}function ta(a,b){for(var c=b.target||b.srcElement;c!=a.wrapper;c=c.parentNode)if(!c||1==c.nodeType&&"true"==c.getAttribute("cm-ignore-events")||c.parentNode==a.sizer&&c!=a.mover)return!0}function fd(a){return a.mover.offsetHeight-a.lineSpace.offsetHeight}function qe(a){if(a.cachedPaddingH)return a.cachedPaddingH;var b=W(a.measure,v("pre",
"x")),b=window.getComputedStyle?window.getComputedStyle(b):b.currentStyle,b={left:parseInt(b.paddingLeft),right:parseInt(b.paddingRight)};isNaN(b.left)||isNaN(b.right)||(a.cachedPaddingH=b);return b}function ma(a){return 30-a.display.nativeBarWidth}function Ma(a){return a.display.scroller.clientWidth-ma(a)-a.display.barWidth}function gd(a){return a.display.scroller.clientHeight-ma(a)-a.display.barHeight}function re(a,b,c){if(a.line==b)return{map:a.measure.map,cache:a.measure.cache};for(var d=0;d<
a.rest.length;d++)if(a.rest[d]==b)return{map:a.measure.maps[d],cache:a.measure.caches[d]};for(b=0;b<a.rest.length;b++)if(D(a.rest[b])>c)return{map:a.measure.maps[b],cache:a.measure.caches[b],before:!0}}function hd(a,b){if(b>=a.display.viewFrom&&b<a.display.viewTo)return a.display.view[Na(a,b)];var c=a.display.externalMeasured;if(c&&b>=c.lineN&&b<c.lineN+c.size)return c}function Wa(a,b){var c=D(b),d=hd(a,c);d&&!d.text?d=null:d&&d.changes&&(le(a,d,c,id(a)),a.curOp.forceUpdate=!0);if(!d){var e;e=ja(b);
d=D(e);e=a.display.externalMeasured=new ke(a.doc,e,d);e.lineN=d;d=e.built=ie(a,e);e.text=d.pre;W(a.display.lineMeasure,d.pre);d=e}c=re(d,b,c);return{line:b,view:d,rect:null,map:c.map,cache:c.cache,before:c.before,hasHeights:!1}}function qa(a,b,c,d,e){b.before&&(c=-1);var f=c+(d||"");if(b.cache.hasOwnProperty(f))a=b.cache[f];else{b.rect||(b.rect=b.view.text.getBoundingClientRect());if(!b.hasHeights){var g=b.view,h=b.rect,k=a.options.lineWrapping,l=k&&Ma(a);if(!g.measure.heights||k&&g.measure.width!=
l){var m=g.measure.heights=[];if(k)for(g.measure.width=l,g=g.text.firstChild.getClientRects(),k=0;k<g.length-1;k++){var l=g[k],n=g[k+1];2<Math.abs(l.bottom-n.bottom)&&m.push((l.bottom+n.top)/2-h.top)}m.push(h.bottom-h.top)}b.hasHeights=!0}m=d;g=se(b.map,c,m);d=g.node;h=g.start;k=g.end;c=g.collapse;var p;if(3==d.nodeType){for(var u=0;4>u;u++){for(;h&&Kc(b.line.text.charAt(g.coverStart+h));)--h;for(;g.coverStart+k<g.coverEnd&&Kc(b.line.text.charAt(g.coverStart+k));)++k;if(C&&9>z&&0==h&&k==g.coverEnd-
g.coverStart)p=d.parentNode.getBoundingClientRect();else{p=$a(d,h,k).getClientRects();k=te;if("left"==m)for(l=0;l<p.length&&(k=p[l]).left==k.right;l++);else for(l=p.length-1;0<=l&&(k=p[l]).left==k.right;l--);p=k}if(p.left||p.right||0==h)break;k=h;--h;c="right"}C&&11>z&&((u=!window.screen||null==screen.logicalXDPI||screen.logicalXDPI==screen.deviceXDPI)||(null!=jd?u=jd:(m=W(a.display.measure,v("span","x")),u=m.getBoundingClientRect(),m=$a(m,0,1).getBoundingClientRect(),u=jd=1<Math.abs(u.left-m.left)),
u=!u),u||(u=screen.logicalXDPI/screen.deviceXDPI,m=screen.logicalYDPI/screen.deviceYDPI,p={left:p.left*u,right:p.right*u,top:p.top*m,bottom:p.bottom*m}))}else 0<h&&(c=m="right"),p=a.options.lineWrapping&&1<(u=d.getClientRects()).length?u["right"==m?u.length-1:0]:d.getBoundingClientRect();!(C&&9>z)||h||p&&(p.left||p.right)||(p=(p=d.parentNode.getClientRects()[0])?{left:p.left,right:p.left+Bb(a.display),top:p.top,bottom:p.bottom}:te);d=p.top-b.rect.top;h=p.bottom-b.rect.top;u=(d+h)/2;m=b.view.measure.heights;
for(g=0;g<m.length-1&&!(u<m[g]);g++);c={left:("right"==c?p.right:p.left)-b.rect.left,right:("left"==c?p.left:p.right)-b.rect.left,top:g?m[g-1]:0,bottom:m[g]};p.left||p.right||(c.bogus=!0);a.options.singleCursorHeightPerLine||(c.rtop=d,c.rbottom=h);a=c;a.bogus||(b.cache[f]=a)}return{left:a.left,right:a.right,top:e?a.rtop:a.top,bottom:e?a.rbottom:a.bottom}}function se(a,b,c){for(var d,e,f,g,h,k,l=0;l<a.length;l+=3){h=a[l];k=a[l+1];if(b<h)e=0,f=1,g="left";else if(b<k)e=b-h,f=e+1;else if(l==a.length-
3||b==k&&a[l+3]>b)f=k-h,e=f-1,b>=k&&(g="right");if(null!=e){d=a[l+2];h==k&&c==(d.insertLeft?"left":"right")&&(g=c);if("left"==c&&0==e)for(;l&&a[l-2]==a[l-3]&&a[l-1].insertLeft;)d=a[(l-=3)+2],g="left";if("right"==c&&e==k-h)for(;l<a.length-3&&a[l+3]==a[l+4]&&!a[l+5].insertLeft;)d=a[(l+=3)+2],g="right";break}}return{node:d,start:e,end:f,collapse:g,coverStart:h,coverEnd:k}}function ue(a){if(a.measure&&(a.measure.cache={},a.measure.heights=null,a.rest))for(var b=0;b<a.rest.length;b++)a.measure.caches[b]=
{}}function ve(a){a.display.externalMeasure=null;aa(a.display.lineMeasure);for(var b=0;b<a.display.view.length;b++)ue(a.display.view[b])}function Cb(a){ve(a);a.display.cachedCharWidth=a.display.cachedTextHeight=a.display.cachedPaddingH=null;a.options.lineWrapping||(a.display.maxLineChanged=!0);a.display.lineNumChars=null}function Ka(a,b,c,d,e){if(!e&&b.widgets)for(e=0;e<b.widgets.length;++e)if(b.widgets[e].above){var f=Ab(b.widgets[e]);c.top+=f;c.bottom+=f}if("line"==d)return c;d||(d="local");b=ka(b);
b="local"==d?b+a.display.lineSpace.offsetTop:b-a.display.viewOffset;if("page"==d||"window"==d)a=a.display.lineSpace.getBoundingClientRect(),b+=a.top+("window"==d?0:window.pageYOffset||(document.documentElement||document.body).scrollTop),d=a.left+("window"==d?0:window.pageXOffset||(document.documentElement||document.body).scrollLeft),c.left+=d,c.right+=d;c.top+=b;c.bottom+=b;return c}function we(a,b,c){if("div"==c)return b;var d=b.left;b=b.top;"page"==c?(d-=window.pageXOffset||(document.documentElement||
document.body).scrollLeft,b-=window.pageYOffset||(document.documentElement||document.body).scrollTop):"local"!=c&&c||(c=a.display.sizer.getBoundingClientRect(),d+=c.left,b+=c.top);a=a.display.lineSpace.getBoundingClientRect();return{left:d-a.left,top:b-a.top}}function jc(a,b,c,d,e){d||(d=r(a.doc,b.line));var f=d;b=b.ch;d=qa(a,Wa(a,d),b,e);return Ka(a,f,d,c)}function fa(a,b,c,d,e,f){function g(b,g){var h=qa(a,e,b,g?"right":"left",f);g?h.left=h.right:h.right=h.left;return Ka(a,d,h,c)}function h(a,b,
d){return g(d?a-1:a,0!=k[b].level%2!=d)}d=d||r(a.doc,b.line);e||(e=Wa(a,d));var k=ya(d),l=b.ch;b=b.sticky;l>=d.text.length?(l=d.text.length,b="before"):0>=l&&(l=0,b="after");if(!k)return g("before"==b?l-1:l,"before"==b);var m=Tc(k,l,b),n=vb,m=h(l,m,"before"==b);null!=n&&(m.other=h(l,n,"before"!=b));return m}function xe(a,b){var c=0;b=t(a.doc,b);a.options.lineWrapping||(c=Bb(a.display)*b.ch);var d=r(a.doc,b.line),e=ka(d)+a.display.lineSpace.offsetTop;return{left:c,right:c,top:e,bottom:e+d.height}}
function kd(a,b,c){var d=a.doc;c+=a.display.viewOffset;if(0>c)return a=q(d.first,0,null),a.xRel=-1,a.outside=!0,a;var e=Ha(d,c),f=d.first+d.size-1;if(e>f)return a=r(d,f).text.length,a=q(d.first+d.size-1,a,null),a.xRel=1,a.outside=!0,a;0>b&&(b=0);for(f=r(d,e);;)if(d=eg(a,f,e,b,c),f=(e=Ia(f,!1))&&e.find(0,!0),e&&(d.ch>f.from.ch||d.ch==f.from.ch&&0<d.xRel))e=D(f=f.to.line);else return d}function Xd(a,b,c,d){var e=b.text.length,f=bc(function(e){return Ka(a,b,qa(a,c,e-1),"line").bottom<=d},e,0),e=bc(function(e){return Ka(a,
b,qa(a,c,e),"line").top>d},f,e);return{begin:f,end:e}}function eg(a,b,c,d,e){e-=ka(b);var f=0,g=b.text.length,h=Wa(a,b);if(ya(b)){if(a.options.lineWrapping){var k;k=Xd(a,b,h,e);f=k.begin;g=k.end;k}c=new q(c,f);var l=fa(a,c,"line",b,h).left;k=l<d?1:-1;var m=l-d,n;do{l=m;n=c;c=Wd(a,b,c,k);if(null==c||c.ch<f||g<=("before"==c.sticky?c.ch-1:c.ch)){c=n;break}m=fa(a,c,"line",b,h).left-d}while(0>k!=0>m&&Math.abs(m)<=Math.abs(l));if(Math.abs(m)>Math.abs(l)){if(0>m==0>l)throw Error("Broke out of infinite loop in coordsCharInner");
c=n}}else f=bc(function(c){var f=Ka(a,b,qa(a,h,c),"line");return f.top>e?(g=Math.min(c,g),!0):f.bottom<=e?!1:f.left>d?!0:f.right<d?!1:d-f.left<f.right-d},f,g),f=Od(b.text,f,1),c=new q(c,f,f==g?"before":"after");f=fa(a,c,"line",b,h);if(e<f.top||f.bottom<e)c.outside=!0;c.xRel=d<f.left?-1:d>f.right?1:0;return c}function Oa(a){if(null!=a.cachedTextHeight)return a.cachedTextHeight;if(null==Pa){Pa=v("pre");for(var b=0;49>b;++b)Pa.appendChild(document.createTextNode("x")),Pa.appendChild(v("br"));Pa.appendChild(document.createTextNode("x"))}W(a.measure,
Pa);b=Pa.offsetHeight/50;3<b&&(a.cachedTextHeight=b);aa(a.measure);return b||1}function Bb(a){if(null!=a.cachedCharWidth)return a.cachedCharWidth;var b=v("span","xxxxxxxxxx"),c=v("pre",[b]);W(a.measure,c);b=b.getBoundingClientRect();b=(b.right-b.left)/10;2<b&&(a.cachedCharWidth=b);return b||10}function id(a){for(var b=a.display,c={},d={},e=b.gutters.clientLeft,f=b.gutters.firstChild,g=0;f;f=f.nextSibling,++g)c[a.options.gutters[g]]=f.offsetLeft+f.clientLeft+e,d[a.options.gutters[g]]=f.clientWidth;
return{fixedPos:ld(b),gutterTotalWidth:b.gutters.offsetWidth,gutterLeft:c,gutterWidth:d,wrapperWidth:b.wrapper.clientWidth}}function ld(a){return a.scroller.getBoundingClientRect().left-a.sizer.getBoundingClientRect().left}function ye(a){var b=Oa(a.display),c=a.options.lineWrapping,d=c&&Math.max(5,a.display.scroller.clientWidth/Bb(a.display)-3);return function(e){if(Ja(a.doc,e))return 0;var f=0;if(e.widgets)for(var g=0;g<e.widgets.length;g++)e.widgets[g].height&&(f+=e.widgets[g].height);return c?
f+(Math.ceil(e.text.length/d)||1)*b:f+b}}function md(a){var b=a.doc,c=ye(a);b.iter(function(a){var b=c(a);b!=a.height&&ia(a,b)})}function Qa(a,b,c,d){var e=a.display;if(!c&&"true"==(b.target||b.srcElement).getAttribute("cm-not-content"))return null;var f,g;c=e.lineSpace.getBoundingClientRect();try{f=b.clientX-c.left,g=b.clientY-c.top}catch(k){return null}b=kd(a,f,g);var h;d&&1==b.xRel&&(h=r(a.doc,b.line).text).length==b.ch&&(d=ba(h,h.length,a.options.tabSize)-h.length,b=q(b.line,Math.max(0,Math.round((f-
qe(a.display).left)/Bb(a.display))-d)));return b}function Na(a,b){if(b>=a.display.viewTo)return null;b-=a.display.viewFrom;if(0>b)return null;for(var c=a.display.view,d=0;d<c.length;d++)if(b-=c[d].size,0>b)return d}function Db(a){a.display.input.showSelection(a.display.input.prepareSelection())}function ze(a,b){for(var c=a.doc,d={},e=d.cursors=document.createDocumentFragment(),f=d.selection=document.createDocumentFragment(),g=0;g<c.sel.ranges.length;g++)if(!1!==b||g!=c.sel.primIndex){var h=c.sel.ranges[g];
if(!(h.from().line>=a.display.viewTo||h.to().line<a.display.viewFrom)){var k=h.empty();(k||a.options.showCursorWhenSelecting)&&Ae(a,h.head,e);k||fg(a,h,f)}}return d}function Ae(a,b,c){b=fa(a,b,"div",null,null,!a.options.singleCursorHeightPerLine);var d=c.appendChild(v("div","\u00a0","CodeMirror-cursor"));d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.height=Math.max(0,b.bottom-b.top)*a.options.cursorHeight+"px";b.other&&(a=c.appendChild(v("div","\u00a0","CodeMirror-cursor CodeMirror-secondarycursor")),
a.style.display="",a.style.left=b.other.left+"px",a.style.top=b.other.top+"px",a.style.height=.85*(b.other.bottom-b.other.top)+"px")}function fg(a,b,c){function d(a,b,d,c){0>b&&(b=0);b=Math.round(b);c=Math.round(c);h.appendChild(v("div",null,"CodeMirror-selected","position: absolute; left: "+a+"px;\n                             top: "+b+"px; width: "+(null==d?m-a:d)+"px;\n                             height: "+(c-b)+"px"))}function e(b,c,e){var f=r(g,b),h=f.text.length,k,n;Rf(ya(f),c||0,null==e?h:
e,function(g,p,u){var t=jc(a,q(b,g),"div",f,"left"),r,v;g==p?(r=t,u=v=t.left):(r=jc(a,q(b,p-1),"div",f,"right"),"rtl"==u&&(u=t,t=r,r=u),u=t.left,v=r.right);null==c&&0==g&&(u=l);3<r.top-t.top&&(d(u,t.top,null,t.bottom),u=l,t.bottom<r.top&&d(u,t.bottom,null,r.top));null==e&&p==h&&(v=m);if(!k||t.top<k.top||t.top==k.top&&t.left<k.left)k=t;if(!n||r.bottom>n.bottom||r.bottom==n.bottom&&r.right>n.right)n=r;u<l+1&&(u=l);d(u,r.top,v-u,r.bottom)});return{start:k,end:n}}var f=a.display,g=a.doc,h=document.createDocumentFragment(),
k=qe(a.display),l=k.left,m=Math.max(f.sizerWidth,Ma(a)-f.sizer.offsetLeft)-k.right,f=b.from();b=b.to();if(f.line==b.line)e(f.line,f.ch,b.ch);else{var n=r(g,f.line),k=r(g,b.line),k=ja(n)==ja(k),f=e(f.line,f.ch,k?n.text.length+1:null).end;b=e(b.line,k?0:null,b.ch).start;k&&(f.top<b.top-2?(d(f.right,f.top,null,f.bottom),d(l,b.top,b.left,b.bottom)):d(f.right,f.top,b.left-f.right,f.bottom));f.bottom<b.top&&d(l,f.bottom,null,b.top)}c.appendChild(h)}function nd(a){if(a.state.focused){var b=a.display;clearInterval(b.blinker);
var c=!0;b.cursorDiv.style.visibility="";0<a.options.cursorBlinkRate?b.blinker=setInterval(function(){return b.cursorDiv.style.visibility=(c=!c)?"":"hidden"},a.options.cursorBlinkRate):0>a.options.cursorBlinkRate&&(b.cursorDiv.style.visibility="hidden")}}function Be(a){a.state.focused||(a.display.input.focus(),od(a))}function gg(a){a.state.delayingBlurEvent=!0;setTimeout(function(){a.state.delayingBlurEvent&&(a.state.delayingBlurEvent=!1,Eb(a))},100)}function od(a,b){a.state.delayingBlurEvent&&(a.state.delayingBlurEvent=
!1);"nocursor"!=a.options.readOnly&&(a.state.focused||(F(a,"focus",a,b),a.state.focused=!0,Va(a.display.wrapper,"CodeMirror-focused"),a.curOp||a.display.selForContextMenu==a.doc.sel||(a.display.input.reset(),L&&setTimeout(function(){return a.display.input.reset(!0)},20)),a.display.input.receivedFocus()),nd(a))}function Eb(a,b){a.state.delayingBlurEvent||(a.state.focused&&(F(a,"blur",a,b),a.state.focused=!1,bb(a.display.wrapper,"CodeMirror-focused")),clearInterval(a.display.blinker),setTimeout(function(){a.state.focused||
(a.display.shift=!1)},150))}function pd(a){var b=a.display,c=b.view;if(b.alignWidgets||b.gutters.firstChild&&a.options.fixedGutter){for(var d=ld(b)-b.scroller.scrollLeft+a.doc.scrollLeft,e=b.gutters.offsetWidth,f=d+"px",g=0;g<c.length;g++)if(!c[g].hidden){a.options.fixedGutter&&(c[g].gutter&&(c[g].gutter.style.left=f),c[g].gutterBackground&&(c[g].gutterBackground.style.left=f));var h=c[g].alignable;if(h)for(var k=0;k<h.length;k++)h[k].style.left=f}a.options.fixedGutter&&(b.gutters.style.left=d+e+
"px")}}function Ce(a){if(!a.options.lineNumbers)return!1;var b=a.doc,b=Mc(a.options,b.first+b.size-1),c=a.display;if(b.length!=c.lineNumChars){var d=c.measure.appendChild(v("div",[v("div",b)],"CodeMirror-linenumber CodeMirror-gutter-elt")),e=d.firstChild.offsetWidth,d=d.offsetWidth-e;c.lineGutter.style.width="";c.lineNumInnerWidth=Math.max(e,c.lineGutter.offsetWidth-d)+1;c.lineNumWidth=c.lineNumInnerWidth+d;c.lineNumChars=c.lineNumInnerWidth?b.length:-1;c.lineGutter.style.width=c.lineNumWidth+"px";
qd(a);return!0}return!1}function kc(a){a=a.display;for(var b=a.lineDiv.offsetTop,c=0;c<a.view.length;c++){var d=a.view[c],e;if(!d.hidden){if(C&&8>z){var f=d.node.offsetTop+d.node.offsetHeight;e=f-b;b=f}else e=d.node.getBoundingClientRect(),e=e.bottom-e.top;f=d.line.height-e;2>e&&(e=Oa(a));if(.001<f||-.001>f)if(ia(d.line,e),De(d.line),d.rest)for(e=0;e<d.rest.length;e++)De(d.rest[e])}}}function De(a){if(a.widgets)for(var b=0;b<a.widgets.length;++b)a.widgets[b].height=a.widgets[b].node.parentNode.offsetHeight}
function rd(a,b,c){var d=c&&null!=c.top?Math.max(0,c.top):a.scroller.scrollTop,d=Math.floor(d-a.lineSpace.offsetTop),e=c&&null!=c.bottom?c.bottom:d+a.wrapper.clientHeight,d=Ha(b,d),e=Ha(b,e);if(c&&c.ensure){var f=c.ensure.from.line;c=c.ensure.to.line;f<d?(d=f,e=Ha(b,ka(r(b,f))+a.wrapper.clientHeight)):Math.min(c,b.lastLine())>=e&&(d=Ha(b,ka(r(b,c))-a.wrapper.clientHeight),e=c)}return{from:d,to:Math.max(e,d+1)}}function Fb(a,b){2>Math.abs(a.doc.scrollTop-b)||(a.doc.scrollTop=b,wa||sd(a,{top:b}),a.display.scroller.scrollTop!=
b&&(a.display.scroller.scrollTop=b),a.display.scrollbars.setScrollTop(b),wa&&sd(a),Gb(a,100))}function cb(a,b,c){(c?b==a.doc.scrollLeft:2>Math.abs(a.doc.scrollLeft-b))||(b=Math.min(b,a.display.scroller.scrollWidth-a.display.scroller.clientWidth),a.doc.scrollLeft=b,pd(a),a.display.scroller.scrollLeft!=b&&(a.display.scroller.scrollLeft=b),a.display.scrollbars.setScrollLeft(b))}function Ee(a){var b=a.wheelDeltaX,c=a.wheelDeltaY;null==b&&a.detail&&a.axis==a.HORIZONTAL_AXIS&&(b=a.detail);null==c&&a.detail&&
a.axis==a.VERTICAL_AXIS?c=a.detail:null==c&&(c=a.wheelDelta);return{x:b,y:c}}function hg(a){a=Ee(a);a.x*=X;a.y*=X;return a}function Fe(a,b){var c=Ee(b),d=c.x,c=c.y,e=a.display,f=e.scroller,g=f.scrollWidth>f.clientWidth,h=f.scrollHeight>f.clientHeight;if(d&&g||c&&h){if(c&&ea&&L){var g=b.target,k=e.view;a:for(;g!=f;g=g.parentNode)for(var l=0;l<k.length;l++)if(k[l].node==g){a.display.currentWheelTarget=g;break a}}!d||wa||ga||null==X?(c&&null!=X&&(h=c*X,g=a.doc.scrollTop,k=g+e.wrapper.clientHeight,0>
h?g=Math.max(0,g+h-50):k=Math.min(a.doc.height,k+h+50),sd(a,{top:g,bottom:k})),20>lc&&(null==e.wheelStartX?(e.wheelStartX=f.scrollLeft,e.wheelStartY=f.scrollTop,e.wheelDX=d,e.wheelDY=c,setTimeout(function(){if(null!=e.wheelStartX){var a=f.scrollLeft-e.wheelStartX,b=f.scrollTop-e.wheelStartY,a=b&&e.wheelDY&&b/e.wheelDY||a&&e.wheelDX&&a/e.wheelDX;e.wheelStartX=e.wheelStartY=null;a&&(X=(X*lc+a)/(lc+1),++lc)}},200)):(e.wheelDX+=d,e.wheelDY+=c))):(c&&h&&Fb(a,Math.max(0,Math.min(f.scrollTop+c*X,f.scrollHeight-
f.clientHeight))),cb(a,Math.max(0,Math.min(f.scrollLeft+d*X,f.scrollWidth-f.clientWidth))),(!c||c&&h)&&P(b),e.wheelStartX=null)}}function Hb(a){var b=a.display,c=b.gutters.offsetWidth,d=Math.round(a.doc.height+fd(a.display));return{clientHeight:b.scroller.clientHeight,viewHeight:b.wrapper.clientHeight,scrollWidth:b.scroller.scrollWidth,clientWidth:b.scroller.clientWidth,viewWidth:b.wrapper.clientWidth,barLeft:a.options.fixedGutter?c:0,docHeight:d,scrollHeight:d+ma(a)+b.barHeight,nativeBarWidth:b.nativeBarWidth,
gutterWidth:c}}function db(a,b){b||(b=Hb(a));var c=a.display.barWidth,d=a.display.barHeight;Ge(a,b);for(var e=0;4>e&&c!=a.display.barWidth||d!=a.display.barHeight;e++)c!=a.display.barWidth&&a.options.lineWrapping&&kc(a),Ge(a,Hb(a)),c=a.display.barWidth,d=a.display.barHeight}function Ge(a,b){var c=a.display,d=c.scrollbars.update(b);c.sizer.style.paddingRight=(c.barWidth=d.right)+"px";c.sizer.style.paddingBottom=(c.barHeight=d.bottom)+"px";c.heightForcer.style.borderBottom=d.bottom+"px solid transparent";
d.right&&d.bottom?(c.scrollbarFiller.style.display="block",c.scrollbarFiller.style.height=d.bottom+"px",c.scrollbarFiller.style.width=d.right+"px"):c.scrollbarFiller.style.display="";d.bottom&&a.options.coverGutterNextToScrollbar&&a.options.fixedGutter?(c.gutterFiller.style.display="block",c.gutterFiller.style.height=d.bottom+"px",c.gutterFiller.style.width=b.gutterWidth+"px"):c.gutterFiller.style.display=""}function He(a){a.display.scrollbars&&(a.display.scrollbars.clear(),a.display.scrollbars.addClass&&
bb(a.display.wrapper,a.display.scrollbars.addClass));a.display.scrollbars=new Ie[a.options.scrollbarStyle](function(b){a.display.wrapper.insertBefore(b,a.display.scrollbarFiller);w(b,"mousedown",function(){a.state.focused&&setTimeout(function(){return a.display.input.focus()},0)});b.setAttribute("cm-not-content","true")},function(b,c){"horizontal"==c?cb(a,b):Fb(a,b)},a);a.display.scrollbars.addClass&&Va(a.display.wrapper,a.display.scrollbars.addClass)}function mc(a,b,c,d,e){var f=a.display,g=Oa(a.display);
0>c&&(c=0);var h=a.curOp&&null!=a.curOp.scrollTop?a.curOp.scrollTop:f.scroller.scrollTop,k=gd(a),l={};e-c>k&&(e=c+k);var m=a.doc.height+fd(f),n=c<g,g=e>m-g;c<h?l.scrollTop=n?0:c:e>h+k&&(c=Math.min(c,(g?m:e)-k),c!=h&&(l.scrollTop=c));h=a.curOp&&null!=a.curOp.scrollLeft?a.curOp.scrollLeft:f.scroller.scrollLeft;a=Ma(a)-(a.options.fixedGutter?f.gutters.offsetWidth:0);(f=d-b>a)&&(d=b+a);10>b?l.scrollLeft=0:b<h?l.scrollLeft=Math.max(0,b-(f?0:10)):d>a+h-3&&(l.scrollLeft=d+(f?0:10)-a);return l}function nc(a,
b,c){null==b&&null==c||oc(a);null!=b&&(a.curOp.scrollLeft=(null==a.curOp.scrollLeft?a.doc.scrollLeft:a.curOp.scrollLeft)+b);null!=c&&(a.curOp.scrollTop=(null==a.curOp.scrollTop?a.doc.scrollTop:a.curOp.scrollTop)+c)}function eb(a){oc(a);var b=a.getCursor(),c=b,d=b;a.options.lineWrapping||(c=b.ch?q(b.line,b.ch-1):b,d=q(b.line,b.ch+1));a.curOp.scrollToPos={from:c,to:d,margin:a.options.cursorScrollMargin,isCursor:!0}}function oc(a){var b=a.curOp.scrollToPos;if(b){a.curOp.scrollToPos=null;var c=xe(a,b.from),
d=xe(a,b.to),b=mc(a,Math.min(c.left,d.left),Math.min(c.top,d.top)-b.margin,Math.max(c.right,d.right),Math.max(c.bottom,d.bottom)+b.margin);a.scrollTo(b.scrollLeft,b.scrollTop)}}function fb(a){a.curOp={cm:a,viewChanged:!1,startHeight:a.doc.height,forceUpdate:!1,updateInput:null,typing:!1,changeObjs:null,cursorActivityHandlers:null,cursorActivityCalled:0,selectionChanged:!1,updateMaxLine:!1,scrollLeft:null,scrollTop:null,scrollToPos:null,focus:!1,id:++ig};a=a.curOp;ab?ab.ops.push(a):a.ownsGroup=ab=
{ops:[a],delayedCallbacks:[]}}function gb(a){bg(a.curOp,function(a){for(var b=0;b<a.ops.length;b++)a.ops[b].cm.curOp=null;a=a.ops;for(b=0;b<a.length;b++){var d=a[b],e=d.cm,f=e.display,g=e.display;!g.scrollbarsClipped&&g.scroller.offsetWidth&&(g.nativeBarWidth=g.scroller.offsetWidth-g.scroller.clientWidth,g.heightForcer.style.height=ma(e)+"px",g.sizer.style.marginBottom=-g.nativeBarWidth+"px",g.sizer.style.borderRightWidth=ma(e)+"px",g.scrollbarsClipped=!0);d.updateMaxLine&&Sc(e);d.mustUpdate=d.viewChanged||
d.forceUpdate||null!=d.scrollTop||d.scrollToPos&&(d.scrollToPos.from.line<f.viewFrom||d.scrollToPos.to.line>=f.viewTo)||f.maxLineChanged&&e.options.lineWrapping;d.update=d.mustUpdate&&new pc(e,d.mustUpdate&&{top:d.scrollTop,ensure:d.scrollToPos},d.forceUpdate)}for(b=0;b<a.length;b++)d=a[b],d.updatedDisplay=d.mustUpdate&&td(d.cm,d.update);for(b=0;b<a.length;b++)if(d=a[b],e=d.cm,f=e.display,d.updatedDisplay&&kc(e),d.barMeasure=Hb(e),f.maxLineChanged&&!e.options.lineWrapping&&(g=f.maxLine.text.length,
g=qa(e,Wa(e,f.maxLine),g,void 0),d.adjustWidthTo=g.left+3,e.display.sizerWidth=d.adjustWidthTo,d.barMeasure.scrollWidth=Math.max(f.scroller.clientWidth,f.sizer.offsetLeft+d.adjustWidthTo+ma(e)+e.display.barWidth),d.maxScrollLeft=Math.max(0,f.sizer.offsetLeft+d.adjustWidthTo-Ma(e))),d.updatedDisplay||d.selectionChanged)d.preparedSelection=f.input.prepareSelection(d.focus);for(b=0;b<a.length;b++)d=a[b],e=d.cm,null!=d.adjustWidthTo&&(e.display.sizer.style.minWidth=d.adjustWidthTo+"px",d.maxScrollLeft<
e.doc.scrollLeft&&cb(e,Math.min(e.display.scroller.scrollLeft,d.maxScrollLeft),!0),e.display.maxLineChanged=!1),f=d.focus&&d.focus==pa()&&(!document.hasFocus||document.hasFocus()),d.preparedSelection&&e.display.input.showSelection(d.preparedSelection,f),(d.updatedDisplay||d.startHeight!=e.doc.height)&&db(e,d.barMeasure),d.updatedDisplay&&ud(e,d.barMeasure),d.selectionChanged&&nd(e),e.state.focused&&d.updateInput&&e.display.input.reset(d.typing),f&&Be(d.cm);for(b=0;b<a.length;b++){var h=void 0,k,d=
a[b],e=d.cm,f=e.display,g=e.doc;d.updatedDisplay&&Je(e,d.update);null==f.wheelStartX||null==d.scrollTop&&null==d.scrollLeft&&!d.scrollToPos||(f.wheelStartX=f.wheelStartY=null);null==d.scrollTop||f.scroller.scrollTop==d.scrollTop&&!d.forceScroll||(g.scrollTop=Math.max(0,Math.min(f.scroller.scrollHeight-f.scroller.clientHeight,d.scrollTop)),f.scrollbars.setScrollTop(g.scrollTop),f.scroller.scrollTop=g.scrollTop);null==d.scrollLeft||f.scroller.scrollLeft==d.scrollLeft&&!d.forceScroll||(g.scrollLeft=
Math.max(0,Math.min(f.scroller.scrollWidth-f.scroller.clientWidth,d.scrollLeft)),f.scrollbars.setScrollLeft(g.scrollLeft),f.scroller.scrollLeft=g.scrollLeft,pd(e));if(d.scrollToPos){k=t(g,d.scrollToPos.from);var l=t(g,d.scrollToPos.to),m=d.scrollToPos.margin;null==m&&(m=0);for(var n=0;5>n;n++){var p=!1,h=fa(e,k),u=l&&l!=k?fa(e,l):h,u=mc(e,Math.min(h.left,u.left),Math.min(h.top,u.top)-m,Math.max(h.left,u.left),Math.max(h.bottom,u.bottom)+m),q=e.doc.scrollTop,r=e.doc.scrollLeft;null!=u.scrollTop&&(Fb(e,
u.scrollTop),1<Math.abs(e.doc.scrollTop-q)&&(p=!0));null!=u.scrollLeft&&(cb(e,u.scrollLeft),1<Math.abs(e.doc.scrollLeft-r)&&(p=!0));if(!p)break}k=h;d.scrollToPos.isCursor&&e.state.focused&&(H(e,"scrollCursorIntoView")||(l=e.display,m=l.sizer.getBoundingClientRect(),h=null,0>k.top+m.top?h=!0:k.bottom+m.top>(window.innerHeight||document.documentElement.clientHeight)&&(h=!1),null==h||jg||(k=v("div","\u200b",null,"position: absolute;\n                         top: "+(k.top-l.viewOffset-e.display.lineSpace.offsetTop)+
"px;\n                         height: "+(k.bottom-k.top+ma(e)+l.barHeight)+"px;\n                         left: "+k.left+"px; width: 2px;"),e.display.lineSpace.appendChild(k),k.scrollIntoView(h),e.display.lineSpace.removeChild(k))))}k=d.maybeHiddenMarkers;h=d.maybeUnhiddenMarkers;if(k)for(l=0;l<k.length;++l)k[l].lines.length||F(k[l],"hide");if(h)for(k=0;k<h.length;++k)h[k].lines.length&&F(h[k],"unhide");f.wrapper.offsetHeight&&(g.scrollTop=e.display.scroller.scrollTop);d.changeObjs&&F(e,"changes",
e,d.changeObjs);d.update&&d.update.finish()}})}function Y(a,b){if(a.curOp)return b();fb(a);try{return b()}finally{gb(a)}}function J(a,b){return function(){if(a.curOp)return b.apply(a,arguments);fb(a);try{return b.apply(a,arguments)}finally{gb(a)}}}function R(a){return function(){if(this.curOp)return a.apply(this,arguments);fb(this);try{return a.apply(this,arguments)}finally{gb(this)}}}function N(a){return function(){var b=this.cm;if(!b||b.curOp)return a.apply(this,arguments);fb(b);try{return a.apply(this,
arguments)}finally{gb(b)}}}function Q(a,b,c,d){null==b&&(b=a.doc.first);null==c&&(c=a.doc.first+a.doc.size);d||(d=0);var e=a.display;d&&c<e.viewTo&&(null==e.updateLineNumbers||e.updateLineNumbers>b)&&(e.updateLineNumbers=b);a.curOp.viewChanged=!0;if(b>=e.viewTo)xa&&Qc(a.doc,b)<e.viewTo&&za(a);else if(c<=e.viewFrom)xa&&Vd(a.doc,c+d)>e.viewFrom?za(a):(e.viewFrom+=d,e.viewTo+=d);else if(b<=e.viewFrom&&c>=e.viewTo)za(a);else if(b<=e.viewFrom){var f=qc(a,c,c+d,1);f?(e.view=e.view.slice(f.index),e.viewFrom=
f.lineN,e.viewTo+=d):za(a)}else if(c>=e.viewTo)(f=qc(a,b,b,-1))?(e.view=e.view.slice(0,f.index),e.viewTo=f.lineN):za(a);else{var f=qc(a,b,b,-1),g=qc(a,c,c+d,1);f&&g?(e.view=e.view.slice(0,f.index).concat(ic(a,f.lineN,g.lineN)).concat(e.view.slice(g.index)),e.viewTo+=d):za(a)}if(a=e.externalMeasured)c<a.lineN?a.lineN+=d:b<a.lineN+a.size&&(e.externalMeasured=null)}function Aa(a,b,c){a.curOp.viewChanged=!0;var d=a.display,e=a.display.externalMeasured;e&&b>=e.lineN&&b<e.lineN+e.size&&(d.externalMeasured=
null);b<d.viewFrom||b>=d.viewTo||(a=d.view[Na(a,b)],null!=a.node&&(a=a.changes||(a.changes=[]),-1==K(a,c)&&a.push(c)))}function za(a){a.display.viewFrom=a.display.viewTo=a.doc.first;a.display.view=[];a.display.viewOffset=0}function qc(a,b,c,d){var e=Na(a,b),f=a.display.view;if(!xa||c==a.doc.first+a.doc.size)return{index:e,lineN:c};for(var g=a.display.viewFrom,h=0;h<e;h++)g+=f[h].size;if(g!=b){if(0<d){if(e==f.length-1)return null;b=g+f[e].size-b;e++}else b=g-b;c+=b}for(;Qc(a.doc,c)!=c;){if(e==(0>d?
0:f.length-1))return null;c+=d*f[e-(0>d?1:0)].size;e+=d}return{index:e,lineN:c}}function Ke(a){a=a.display.view;for(var b=0,c=0;c<a.length;c++){var d=a[c];d.hidden||d.node&&!d.changes||++b}return b}function Gb(a,b){a.doc.mode.startState&&a.doc.frontier<a.display.viewTo&&a.state.highlight.set(b,Gc(kg,a))}function kg(a){var b=a.doc;b.frontier<b.first&&(b.frontier=b.first);if(!(b.frontier>=a.display.viewTo)){var c=+new Date+a.options.workTime,d=ra(b.mode,xb(a,b.frontier)),e=[];b.iter(b.frontier,Math.min(b.first+
b.size,a.display.viewTo+500),function(f){if(b.frontier>=a.display.viewFrom){var g=f.styles,h=f.text.length>a.options.maxHighlightLength,k=be(a,f,h?ra(b.mode,d):d,!0);f.styles=k.styles;var l=f.styleClasses;(k=k.classes)?f.styleClasses=k:l&&(f.styleClasses=null);l=!g||g.length!=f.styles.length||l!=k&&(!l||!k||l.bgClass!=k.bgClass||l.textClass!=k.textClass);for(k=0;!l&&k<g.length;++k)l=g[k]!=f.styles[k];l&&e.push(b.frontier);f.stateAfter=h?d:ra(b.mode,d)}else f.text.length<=a.options.maxHighlightLength&&
bd(a,f.text,d),f.stateAfter=0==b.frontier%5?ra(b.mode,d):null;++b.frontier;if(+new Date>c)return Gb(a,a.options.workDelay),!0});e.length&&Y(a,function(){for(var b=0;b<e.length;b++)Aa(a,e[b],"text")})}}function td(a,b){var c=a.display,d=a.doc;if(b.editorIsHidden)return za(a),!1;if(!b.force&&b.visible.from>=c.viewFrom&&b.visible.to<=c.viewTo&&(null==c.updateLineNumbers||c.updateLineNumbers>=c.viewTo)&&c.renderedView==c.view&&0==Ke(a))return!1;Ce(a)&&(za(a),b.dims=id(a));var e=d.first+d.size,f=Math.max(b.visible.from-
a.options.viewportMargin,d.first),g=Math.min(e,b.visible.to+a.options.viewportMargin);c.viewFrom<f&&20>f-c.viewFrom&&(f=Math.max(d.first,c.viewFrom));c.viewTo>g&&20>c.viewTo-g&&(g=Math.min(e,c.viewTo));xa&&(f=Qc(a.doc,f),g=Vd(a.doc,g));d=f!=c.viewFrom||g!=c.viewTo||c.lastWrapHeight!=b.wrapperHeight||c.lastWrapWidth!=b.wrapperWidth;e=a.display;0==e.view.length||f>=e.viewTo||g<=e.viewFrom?(e.view=ic(a,f,g),e.viewFrom=f):(e.viewFrom>f?e.view=ic(a,f,e.viewFrom).concat(e.view):e.viewFrom<f&&(e.view=e.view.slice(Na(a,
f))),e.viewFrom=f,e.viewTo<g?e.view=e.view.concat(ic(a,e.viewTo,g)):e.viewTo>g&&(e.view=e.view.slice(0,Na(a,g))));e.viewTo=g;c.viewOffset=ka(r(a.doc,c.viewFrom));a.display.mover.style.top=c.viewOffset+"px";g=Ke(a);if(!d&&0==g&&!b.force&&c.renderedView==c.view&&(null==c.updateLineNumbers||c.updateLineNumbers>=c.viewTo))return!1;f=pa();4<g&&(c.lineDiv.style.display="none");lg(a,c.updateLineNumbers,b.dims);4<g&&(c.lineDiv.style.display="");c.renderedView=c.view;f&&pa()!=f&&f.offsetHeight&&f.focus();
aa(c.cursorDiv);aa(c.selectionDiv);c.gutters.style.height=c.sizer.style.minHeight=0;d&&(c.lastWrapHeight=b.wrapperHeight,c.lastWrapWidth=b.wrapperWidth,Gb(a,400));c.updateLineNumbers=null;return!0}function Je(a,b){for(var c=b.viewport,d=!0;;d=!1){if(!d||!a.options.lineWrapping||b.oldDisplayWidth==Ma(a))if(c&&null!=c.top&&(c={top:Math.min(a.doc.height+fd(a.display)-gd(a),c.top)}),b.visible=rd(a.display,a.doc,c),b.visible.from>=a.display.viewFrom&&b.visible.to<=a.display.viewTo)break;if(!td(a,b))break;
kc(a);d=Hb(a);Db(a);db(a,d);ud(a,d)}b.signal(a,"update",a);if(a.display.viewFrom!=a.display.reportedViewFrom||a.display.viewTo!=a.display.reportedViewTo)b.signal(a,"viewportChange",a,a.display.viewFrom,a.display.viewTo),a.display.reportedViewFrom=a.display.viewFrom,a.display.reportedViewTo=a.display.viewTo}function sd(a,b){var c=new pc(a,b);if(td(a,c)){kc(a);Je(a,c);var d=Hb(a);Db(a);db(a,d);ud(a,d);c.finish()}}function lg(a,b,c){function d(b){var d=b.nextSibling;L&&ea&&a.display.currentWheelTarget==
b?b.style.display="none":b.parentNode.removeChild(b);return d}for(var e=a.display,f=a.options.lineNumbers,g=e.lineDiv,h=g.firstChild,k=e.view,e=e.viewFrom,l=0;l<k.length;l++){var m=k[l];if(!m.hidden)if(m.node&&m.node.parentNode==g){for(;h!=m.node;)h=d(h);h=f&&null!=b&&b<=e&&m.lineNumber;m.changes&&(-1<K(m.changes,"gutter")&&(h=!1),le(a,m,e,c));h&&(aa(m.lineNumber),m.lineNumber.appendChild(document.createTextNode(Mc(a.options,e))));h=m.node.nextSibling}else{var n=dg(a,m,e,c);g.insertBefore(n,h)}e+=
m.size}for(;h;)h=d(h)}function qd(a){a.display.sizer.style.marginLeft=a.display.gutters.offsetWidth+"px"}function ud(a,b){a.display.sizer.style.minHeight=b.docHeight+"px";a.display.heightForcer.style.top=b.docHeight+"px";a.display.gutters.style.height=b.docHeight+a.display.barHeight+ma(a)+"px"}function Le(a){var b=a.display.gutters,c=a.options.gutters;aa(b);for(var d=0;d<c.length;++d){var e=c[d],f=b.appendChild(v("div",null,"CodeMirror-gutter "+e));"CodeMirror-linenumbers"==e&&(a.display.lineGutter=
f,f.style.width=(a.display.lineNumWidth||1)+"px")}b.style.display=d?"":"none";qd(a)}function vd(a){var b=K(a.gutters,"CodeMirror-linenumbers");-1==b&&a.lineNumbers?a.gutters=a.gutters.concat(["CodeMirror-linenumbers"]):-1<b&&!a.lineNumbers&&(a.gutters=a.gutters.slice(0),a.gutters.splice(b,1))}function ha(a,b){var c=a[b];a.sort(function(a,b){return x(a.from(),b.from())});b=K(a,c);for(c=1;c<a.length;c++){var d=a[c],e=a[c-1];if(0<=x(e.to(),d.from())){var f=dc(e.from(),d.from()),g=cc(e.to(),d.to()),d=
e.empty()?d.from()==d.head:e.from()==e.head;c<=b&&--b;a.splice(--c,2,new A(d?g:f,d?f:g))}}return new Z(a,b)}function ua(a,b){return new Z([new A(a,b||a)],0)}function Ba(a){return a.text?q(a.from.line+a.text.length-1,B(a.text).length+(1==a.text.length?a.from.ch:0)):a.to}function Me(a,b){if(0>x(a,b.from))return a;if(0>=x(a,b.to))return Ba(b);var c=a.line+b.text.length-(b.to.line-b.from.line)-1,d=a.ch;a.line==b.to.line&&(d+=Ba(b).ch-b.to.ch);return q(c,d)}function wd(a,b){for(var c=[],d=0;d<a.sel.ranges.length;d++){var e=
a.sel.ranges[d];c.push(new A(Me(e.anchor,b),Me(e.head,b)))}return ha(c,a.sel.primIndex)}function Ne(a,b,c){return a.line==b.line?q(c.line,a.ch-b.ch+c.ch):q(c.line+(a.line-b.line),a.ch)}function xd(a){a.doc.mode=$c(a.options,a.doc.modeOption);Ib(a)}function Ib(a){a.doc.iter(function(a){a.stateAfter&&(a.stateAfter=null);a.styles&&(a.styles=null)});a.doc.frontier=a.doc.first;Gb(a,100);a.state.modeGen++;a.curOp&&Q(a)}function Oe(a,b){return 0==b.from.ch&&0==b.to.ch&&""==B(b.text)&&(!a.cm||a.cm.options.wholeLineUpdateBefore)}
function yd(a,b,c,d){function e(a,c,e){a.text=c;a.stateAfter&&(a.stateAfter=null);a.styles&&(a.styles=null);null!=a.order&&(a.order=null);Rd(a);Sd(a,e);c=d?d(a):1;c!=a.height&&ia(a,c);M(a,"change",a,b)}function f(a,b){for(var e=[],f=a;f<b;++f)e.push(new hb(k[f],c?c[f]:null,d));return e}var g=b.from,h=b.to,k=b.text,l=r(a,g.line),m=r(a,h.line),n=B(k),p=c?c[k.length-1]:null,u=h.line-g.line;b.full?(a.insert(0,f(0,k.length)),a.remove(k.length,a.size-k.length)):Oe(a,b)?(h=f(0,k.length-1),e(m,m.text,p),
u&&a.remove(g.line,u),h.length&&a.insert(g.line,h)):l==m?1==k.length?e(l,l.text.slice(0,g.ch)+n+l.text.slice(h.ch),p):(u=f(1,k.length-1),u.push(new hb(n+l.text.slice(h.ch),p,d)),e(l,l.text.slice(0,g.ch)+k[0],c?c[0]:null),a.insert(g.line+1,u)):1==k.length?(e(l,l.text.slice(0,g.ch)+k[0]+m.text.slice(h.ch),c?c[0]:null),a.remove(g.line+1,u)):(e(l,l.text.slice(0,g.ch)+k[0],c?c[0]:null),e(m,n+m.text.slice(h.ch),p),p=f(1,k.length-1),1<u&&a.remove(g.line+1,u-1),a.insert(g.line+1,p));M(a,"change",a,b)}function Ra(a,
b,c){function d(a,f,g){if(a.linked)for(var e=0;e<a.linked.length;++e){var k=a.linked[e];if(k.doc!=f){var l=g&&k.sharedHist;if(!c||l)b(k.doc,l),d(k.doc,a,l)}}}d(a,null,!0)}function Pe(a,b){if(b.cm)throw Error("This document is already in use.");a.doc=b;b.cm=a;md(a);xd(a);a.options.lineWrapping||Sc(a);a.options.mode=b.modeOption;Q(a)}function rc(a){this.done=[];this.undone=[];this.undoDepth=Infinity;this.lastModTime=this.lastSelTime=0;this.lastOrigin=this.lastSelOrigin=this.lastOp=this.lastSelOp=null;
this.generation=this.maxGeneration=a||1}function zd(a,b){var c={from:Oc(b.from),to:Ba(b),text:Ga(a,b.from,b.to)};Qe(a,c,b.from.line,b.to.line+1);Ra(a,function(a){return Qe(a,c,b.from.line,b.to.line+1)},!0);return c}function Re(a){for(;a.length;)if(B(a).ranges)a.pop();else break}function Se(a,b,c,d){var e=a.history;e.undone.length=0;var f=+new Date,g,h,k;if(k=e.lastOp==d||e.lastOrigin==b.origin&&b.origin&&("+"==b.origin.charAt(0)&&a.cm&&e.lastModTime>f-a.cm.options.historyEventDelay||"*"==b.origin.charAt(0)))e.lastOp==
d?(Re(e.done),g=B(e.done)):e.done.length&&!B(e.done).ranges?g=B(e.done):1<e.done.length&&!e.done[e.done.length-2].ranges?(e.done.pop(),g=B(e.done)):g=void 0,k=g;if(k)h=B(g.changes),0==x(b.from,b.to)&&0==x(b.from,h.to)?h.to=Ba(b):g.changes.push(zd(a,b));else for((g=B(e.done))&&g.ranges||sc(a.sel,e.done),g={changes:[zd(a,b)],generation:e.generation},e.done.push(g);e.done.length>e.undoDepth;)e.done.shift(),e.done[0].ranges||e.done.shift();e.done.push(c);e.generation=++e.maxGeneration;e.lastModTime=e.lastSelTime=
f;e.lastOp=e.lastSelOp=d;e.lastOrigin=e.lastSelOrigin=b.origin;h||F(a,"historyAdded")}function sc(a,b){var c=B(b);c&&c.ranges&&c.equals(a)||b.push(a)}function Qe(a,b,c,d){var e=b["spans_"+a.id],f=0;a.iter(Math.max(a.first,c),Math.min(a.first+a.size,d),function(d){d.markedSpans&&((e||(e=b["spans_"+a.id]={}))[f]=d.markedSpans);++f})}function mg(a){if(!a)return null;for(var b,c=0;c<a.length;++c)a[c].marker.explicitlyCleared?b||(b=a.slice(0,c)):b&&b.push(a[c]);return b?b.length?b:null:a}function Te(a,
b){var c;if(c=b["spans_"+a.id]){for(var d=[],e=0;e<b.text.length;++e)d.push(mg(c[e]));c=d}else c=null;d=Pc(a,b);if(!c)return d;if(!d)return c;for(e=0;e<c.length;++e){var f=c[e],g=d[e];if(f&&g){var h=0;a:for(;h<g.length;++h){for(var k=g[h],l=0;l<f.length;++l)if(f[l].marker==k.marker)continue a;f.push(k)}}else g&&(c[e]=g)}return c}function ib(a,b,c){for(var d=[],e=0;e<a.length;++e){var f=a[e];if(f.ranges)d.push(c?Z.prototype.deepCopy.call(f):f);else{var f=f.changes,g=[];d.push({changes:g});for(var h=
0;h<f.length;++h){var k=f[h],l;g.push({from:k.from,to:k.to,text:k.text});if(b)for(var m in k)(l=m.match(/^spans_(\d+)$/))&&-1<K(b,Number(l[1]))&&(B(g)[m]=k[m],delete k[m])}}}return d}function Jb(a,b,c,d){return a.cm&&a.cm.display.shift||a.extend?(a=b.anchor,d&&(b=0>x(c,a),b!=0>x(d,a)?(a=c,c=d):b!=0>x(c,d)&&(c=d)),new A(a,c)):new A(d||c,c)}function tc(a,b,c,d){O(a,new Z([Jb(a,a.sel.primary(),b,c)],0),d)}function Ue(a,b,c){for(var d=[],e=0;e<a.sel.ranges.length;e++)d[e]=Jb(a,a.sel.ranges[e],b[e],null);
b=ha(d,a.sel.primIndex);O(a,b,c)}function Ad(a,b,c,d){var e=a.sel.ranges.slice(0);e[b]=c;O(a,ha(e,a.sel.primIndex),d)}function ng(a,b,c){c={ranges:b.ranges,update:function(b){this.ranges=[];for(var d=0;d<b.length;d++)this.ranges[d]=new A(t(a,b[d].anchor),t(a,b[d].head))},origin:c&&c.origin};F(a,"beforeSelectionChange",a,c);a.cm&&F(a.cm,"beforeSelectionChange",a.cm,c);return c.ranges!=b.ranges?ha(c.ranges,c.ranges.length-1):b}function Ve(a,b,c){var d=a.history.done,e=B(d);e&&e.ranges?(d[d.length-1]=
b,uc(a,b,c)):O(a,b,c)}function O(a,b,c){uc(a,b,c);b=a.sel;var d=a.cm?a.cm.curOp.id:NaN,e=a.history,f=c&&c.origin,g;if(!(g=d==e.lastSelOp)&&(g=f&&e.lastSelOrigin==f)&&!(g=e.lastModTime==e.lastSelTime&&e.lastOrigin==f)){g=B(e.done);var h=f.charAt(0);g="*"==h||"+"==h&&g.ranges.length==b.ranges.length&&g.somethingSelected()==b.somethingSelected()&&new Date-a.history.lastSelTime<=(a.cm?a.cm.options.historyEventDelay:500)}g?e.done[e.done.length-1]=b:sc(b,e.done);e.lastSelTime=+new Date;e.lastSelOrigin=
f;e.lastSelOp=d;c&&!1!==c.clearRedo&&Re(e.undone)}function uc(a,b,c){if(ca(a,"beforeSelectionChange")||a.cm&&ca(a.cm,"beforeSelectionChange"))b=ng(a,b,c);var d=c&&c.bias||(0>x(b.primary().head,a.sel.primary().head)?-1:1);We(a,Xe(a,b,d,!0));c&&!1===c.scroll||!a.cm||eb(a.cm)}function We(a,b){b.equals(a.sel)||(a.sel=b,a.cm&&(a.cm.curOp.updateInput=a.cm.curOp.selectionChanged=!0,Yd(a.cm)),M(a,"cursorActivity",a))}function Ye(a){We(a,Xe(a,a.sel,null,!1),na)}function Xe(a,b,c,d){for(var e,f=0;f<b.ranges.length;f++){var g=
b.ranges[f],h=b.ranges.length==a.sel.ranges.length&&a.sel.ranges[f],k=Bd(a,g.anchor,h&&h.anchor,c,d),h=Bd(a,g.head,h&&h.head,c,d);if(e||k!=g.anchor||h!=g.head)e||(e=b.ranges.slice(0,f)),e[f]=new A(k,h)}return e?ha(e,b.primIndex):b}function jb(a,b,c,d,e){var f=r(a,b.line);if(f.markedSpans)for(var g=0;g<f.markedSpans.length;++g){var h=f.markedSpans[g],k=h.marker;if((null==h.from||(k.inclusiveLeft?h.from<=b.ch:h.from<b.ch))&&(null==h.to||(k.inclusiveRight?h.to>=b.ch:h.to>b.ch))){if(e&&(F(k,"beforeCursorEnter"),
k.explicitlyCleared))if(f.markedSpans){--g;continue}else break;if(k.atomic){if(c){g=k.find(0>d?1:-1);h=void 0;if(0>d?k.inclusiveRight:k.inclusiveLeft)g=Ze(a,g,-d,g&&g.line==b.line?f:null);if(g&&g.line==b.line&&(h=x(g,c))&&(0>d?0>h:0<h))return jb(a,g,b,d,e)}c=k.find(0>d?-1:1);if(0>d?k.inclusiveLeft:k.inclusiveRight)c=Ze(a,c,d,c.line==b.line?f:null);return c?jb(a,c,b,d,e):null}}}return b}function Bd(a,b,c,d,e){d=d||1;b=jb(a,b,c,d,e)||!e&&jb(a,b,c,d,!0)||jb(a,b,c,-d,e)||!e&&jb(a,b,c,-d,!0);return b?
b:(a.cantEdit=!0,q(a.first,0))}function Ze(a,b,c,d){return 0>c&&0==b.ch?b.line>a.first?t(a,q(b.line-1)):null:0<c&&b.ch==(d||r(a,b.line)).text.length?b.line<a.first+a.size-1?q(b.line+1,0):null:new q(b.line,b.ch+c)}function $e(a){a.setSelection(q(a.firstLine(),0),q(a.lastLine()),na)}function af(a,b,c){var d={canceled:!1,from:b.from,to:b.to,text:b.text,origin:b.origin,cancel:function(){return d.canceled=!0}};c&&(d.update=function(b,c,g,h){b&&(d.from=t(a,b));c&&(d.to=t(a,c));g&&(d.text=g);void 0!==h&&
(d.origin=h)});F(a,"beforeChange",a,d);a.cm&&F(a.cm,"beforeChange",a.cm,d);return d.canceled?null:{from:d.from,to:d.to,text:d.text,origin:d.origin}}function kb(a,b,c){if(a.cm){if(!a.cm.curOp)return J(a.cm,kb)(a,b,c);if(a.cm.state.suppressEdits)return}if(ca(a,"beforeChange")||a.cm&&ca(a.cm,"beforeChange"))if(b=af(a,b,!0),!b)return;if(c=bf&&!c&&Qf(a,b.from,b.to))for(var d=c.length-1;0<=d;--d)cf(a,{from:c[d].from,to:c[d].to,text:d?[""]:b.text});else cf(a,b)}function cf(a,b){if(1!=b.text.length||""!=
b.text[0]||0!=x(b.from,b.to)){var c=wd(a,b);Se(a,b,c,a.cm?a.cm.curOp.id:NaN);Kb(a,b,c,Pc(a,b));var d=[];Ra(a,function(a,c){c||-1!=K(d,a.history)||(df(a.history,b),d.push(a.history));Kb(a,b,null,Pc(a,b))})}}function vc(a,b,c){if(!a.cm||!a.cm.state.suppressEdits||c){for(var d=a.history,e,f=a.sel,g="undo"==b?d.done:d.undone,h="undo"==b?d.undone:d.done,k=0;k<g.length&&(e=g[k],c?!e.ranges||e.equals(a.sel):e.ranges);k++);if(k!=g.length){for(d.lastOrigin=d.lastSelOrigin=null;;)if(e=g.pop(),e.ranges){sc(e,
h);if(c&&!e.equals(a.sel)){O(a,e,{clearRedo:!1});return}f=e}else break;var l=[];sc(f,h);h.push({changes:l,generation:d.generation});d.generation=e.generation||++d.maxGeneration;var m=ca(a,"beforeChange")||a.cm&&ca(a.cm,"beforeChange");c=function(d){var c=e.changes[d];c.origin=b;if(m&&!af(a,c,!1))return g.length=0,{};l.push(zd(a,c));var f=d?wd(a,c):B(g);Kb(a,c,f,Te(a,c));!d&&a.cm&&a.cm.scrollIntoView({from:c.from,to:Ba(c)});var h=[];Ra(a,function(a,b){b||-1!=K(h,a.history)||(df(a.history,c),h.push(a.history));
Kb(a,c,null,Te(a,c))})};for(d=e.changes.length-1;0<=d;--d)if(f=c(d))return f.v}}}function ef(a,b){if(0!=b&&(a.first+=b,a.sel=new Z($b(a.sel.ranges,function(a){return new A(q(a.anchor.line+b,a.anchor.ch),q(a.head.line+b,a.head.ch))}),a.sel.primIndex),a.cm)){Q(a.cm,a.first,a.first-b,b);for(var c=a.cm.display,d=c.viewFrom;d<c.viewTo;d++)Aa(a.cm,d,"gutter")}}function Kb(a,b,c,d){if(a.cm&&!a.cm.curOp)return J(a.cm,Kb)(a,b,c,d);if(b.to.line<a.first)ef(a,b.text.length-1-(b.to.line-b.from.line));else if(!(b.from.line>
a.lastLine())){if(b.from.line<a.first){var e=b.text.length-1-(a.first-b.from.line);ef(a,e);b={from:q(a.first,0),to:q(b.to.line+e,b.to.ch),text:[B(b.text)],origin:b.origin}}e=a.lastLine();b.to.line>e&&(b={from:b.from,to:q(e,r(a,e).text.length),text:[b.text[0]],origin:b.origin});b.removed=Ga(a,b.from,b.to);c||(c=wd(a,b));a.cm?og(a.cm,b,d):yd(a,b,d);uc(a,c,na)}}function og(a,b,c){var d=a.doc,e=a.display,f=b.from,g=b.to,h=!1,k=f.line;a.options.lineWrapping||(k=D(ja(r(d,f.line))),d.iter(k,g.line+1,function(a){if(a==
e.maxLine)return h=!0}));-1<d.sel.contains(b.from,b.to)&&Yd(a);yd(d,b,c,ye(a));a.options.lineWrapping||(d.iter(k,f.line+b.text.length,function(a){var b=fc(a);b>e.maxLineLength&&(e.maxLine=a,e.maxLineLength=b,e.maxLineChanged=!0,h=!1)}),h&&(a.curOp.updateMaxLine=!0));d.frontier=Math.min(d.frontier,f.line);Gb(a,400);c=b.text.length-(g.line-f.line)-1;b.full?Q(a):f.line!=g.line||1!=b.text.length||Oe(a.doc,b)?Q(a,f.line,g.line+1,c):Aa(a,f.line,"text");c=ca(a,"changes");if((d=ca(a,"change"))||c)b={from:f,
to:g,text:b.text,removed:b.removed,origin:b.origin},d&&M(a,"change",a,b),c&&(a.curOp.changeObjs||(a.curOp.changeObjs=[])).push(b);a.display.selForContextMenu=null}function lb(a,b,c,d,e){d||(d=c);if(0>x(d,c)){var f=d;d=c;c=f}"string"==typeof b&&(b=a.splitLines(b));kb(a,{from:c,to:d,text:b,origin:e})}function ff(a,b,c,d){c<a.line?a.line+=d:b<a.line&&(a.line=b,a.ch=0)}function gf(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e],g=!0;if(f.ranges)for(f.copied||(f=a[e]=f.deepCopy(),f.copied=!0),g=0;g<f.ranges.length;g++)ff(f.ranges[g].anchor,
b,c,d),ff(f.ranges[g].head,b,c,d);else{for(var h=0;h<f.changes.length;++h){var k=f.changes[h];if(c<k.from.line)k.from=q(k.from.line+d,k.from.ch),k.to=q(k.to.line+d,k.to.ch);else if(b<=k.to.line){g=!1;break}}g||(a.splice(0,e+1),e=0)}}}function df(a,b){var c=b.from.line,d=b.to.line,e=b.text.length-(d-c)-1;gf(a.done,c,d,e);gf(a.undone,c,d,e)}function Lb(a,b,c,d){var e=b,f=b;"number"==typeof b?f=r(a,Math.max(a.first,Math.min(b,a.first+a.size-1))):e=D(b);if(null==e)return null;d(f,e)&&a.cm&&Aa(a.cm,e,
c);return f}function pg(a,b,c,d){var e=new Mb(a,c,d),f=a.cm;f&&e.noHScroll&&(f.display.alignWidgets=!0);Lb(a,b,"widget",function(b){var d=b.widgets||(b.widgets=[]);null==e.insertAt?d.push(e):d.splice(Math.min(d.length-1,Math.max(0,e.insertAt)),0,e);e.line=b;f&&!Ja(a,b)&&(d=ka(b)<a.scrollTop,ia(b,b.height+Ab(e)),d&&nc(f,null,e.height),f.curOp.forceUpdate=!0);return!0});M(f,"lineWidgetAdded",f,e,"number"==typeof b?b:D(b));return e}function mb(a,b,c,d,e){if(d&&d.shared)return qg(a,b,c,d,e);if(a.cm&&
!a.cm.curOp)return J(a.cm,mb)(a,b,c,d,e);var f=new Ca(a,e);e=x(b,c);d&&Fa(d,f,!1);if(0<e||0==e&&!1!==f.clearWhenEmpty)return f;f.replacedWith&&(f.collapsed=!0,f.widgetNode=v("span",[f.replacedWith],"CodeMirror-widget"),f.widgetNode.setAttribute("role","presentation"),d.handleMouseEvents||f.widgetNode.setAttribute("cm-ignore-events","true"),d.insertLeft&&(f.widgetNode.insertLeft=!0));if(f.collapsed){if(Ud(a,b.line,b,c,f)||b.line!=c.line&&Ud(a,c.line,b,c,f))throw Error("Inserting collapsed marker partially overlapping an existing one");
xa=!0}f.addToHistory&&Se(a,{from:b,to:c,origin:"markText"},a.sel,NaN);var g=b.line,h=a.cm,k;a.iter(g,c.line+1,function(a){h&&f.collapsed&&!h.options.lineWrapping&&ja(a)==h.display.maxLine&&(k=!0);f.collapsed&&g!=b.line&&ia(a,0);var d=new ec(f,g==b.line?b.ch:null,g==c.line?c.ch:null);a.markedSpans=a.markedSpans?a.markedSpans.concat([d]):[d];d.marker.attachLine(a);++g});f.collapsed&&a.iter(b.line,c.line+1,function(b){Ja(a,b)&&ia(b,0)});f.clearOnEnter&&w(f,"beforeCursorEnter",function(){return f.clear()});
f.readOnly&&(bf=!0,(a.history.done.length||a.history.undone.length)&&a.clearHistory());f.collapsed&&(f.id=++hf,f.atomic=!0);if(h){k&&(h.curOp.updateMaxLine=!0);if(f.collapsed)Q(h,b.line,c.line+1);else if(f.className||f.title||f.startStyle||f.endStyle||f.css)for(d=b.line;d<=c.line;d++)Aa(h,d,"text");f.atomic&&Ye(h.doc);M(h,"markerAdded",h,f)}return f}function qg(a,b,c,d,e){d=Fa(d);d.shared=!1;var f=[mb(a,b,c,d,e)],g=f[0],h=d.widgetNode;Ra(a,function(a){h&&(d.widgetNode=h.cloneNode(!0));f.push(mb(a,
t(a,b),t(a,c),d,e));for(var k=0;k<a.linked.length;++k)if(a.linked[k].isParent)return;g=B(f)});return new Nb(f,g)}function jf(a){return a.findMarks(q(a.first,0),a.clipPos(q(a.lastLine())),function(a){return a.parent})}function rg(a){for(var b=function(b){b=a[b];var d=[b.primary.doc];Ra(b.primary.doc,function(a){return d.push(a)});for(var c=0;c<b.markers.length;c++){var g=b.markers[c];-1==K(d,g.doc)&&(g.parent=null,b.markers.splice(c--,1))}},c=0;c<a.length;c++)b(c)}function sg(a){var b=this;kf(b);if(!H(b,
a)&&!ta(b.display,a)){P(a);C&&(lf=+new Date);var c=Qa(b,a,!0),d=a.dataTransfer.files;if(c&&!b.isReadOnly())if(d&&d.length&&window.FileReader&&window.File)for(var e=d.length,f=Array(e),g=0,h=function(a,d){if(!b.options.allowDropFileTypes||-1!=K(b.options.allowDropFileTypes,a.type)){var h=new FileReader;h.onload=J(b,function(){var a=h.result;/[\x00-\x08\x0e-\x1f]{2}/.test(a)&&(a="");f[d]=a;++g==e&&(c=t(b.doc,c),a={from:c,to:c,text:b.doc.splitLines(f.join(b.doc.lineSeparator())),origin:"paste"},kb(b.doc,
a),Ve(b.doc,ua(c,Ba(a))))});h.readAsText(a)}},k=0;k<e;++k)h(d[k],k);else if(b.state.draggingText&&-1<b.doc.sel.contains(c))b.state.draggingText(a),setTimeout(function(){return b.display.input.focus()},20);else try{if(h=a.dataTransfer.getData("Text")){b.state.draggingText&&!b.state.draggingText.copy&&(k=b.listSelections());uc(b.doc,ua(c,c));if(k)for(d=0;d<k.length;++d)lb(b.doc,"",k[d].anchor,k[d].head,"drag");b.replaceSelection(h,"around","paste");b.display.input.focus()}}catch(l){}}}function kf(a){a.display.dragCursor&&
(a.display.lineSpace.removeChild(a.display.dragCursor),a.display.dragCursor=null)}function mf(a){if(document.body.getElementsByClassName)for(var b=document.body.getElementsByClassName("CodeMirror"),c=0;c<b.length;c++){var d=b[c].CodeMirror;d&&a(d)}}function tg(){var a;w(window,"resize",function(){null==a&&(a=setTimeout(function(){a=null;mf(ug)},100))});w(window,"blur",function(){return mf(Eb)})}function ug(a){var b=a.display;if(b.lastWrapHeight!=b.wrapper.clientHeight||b.lastWrapWidth!=b.wrapper.clientWidth)b.cachedCharWidth=
b.cachedTextHeight=b.cachedPaddingH=null,b.scrollbarsClipped=!1,a.setSize()}function vg(a){var b=a.split(/-(?!$)/);a=b[b.length-1];for(var c,d,e,f,g=0;g<b.length-1;g++){var h=b[g];if(/^(cmd|meta|m)$/i.test(h))f=!0;else if(/^a(lt)?$/i.test(h))c=!0;else if(/^(c|ctrl|control)$/i.test(h))d=!0;else if(/^s(hift)?$/i.test(h))e=!0;else throw Error("Unrecognized modifier name: "+h);}c&&(a="Alt-"+a);d&&(a="Ctrl-"+a);f&&(a="Cmd-"+a);e&&(a="Shift-"+a);return a}function wg(a){var b={},c;for(c in a)if(a.hasOwnProperty(c)){var d=
a[c];if(!/^(name|fallthrough|(de|at)tach)$/.test(c)){if("..."!=d)for(var e=$b(c.split(" "),vg),f=0;f<e.length;f++){var g,h;f==e.length-1?(h=e.join(" "),g=d):(h=e.slice(0,f+1).join(" "),g="...");var k=b[h];if(!k)b[h]=g;else if(k!=g)throw Error("Inconsistent bindings for "+h);}delete a[c]}}for(var l in b)a[l]=b[l];return a}function nb(a,b,c,d){b=wc(b);var e=b.call?b.call(a,d):b[a];if(!1===e)return"nothing";if("..."===e)return"multi";if(null!=e&&c(e))return"handled";if(b.fallthrough){if("[object Array]"!=
Object.prototype.toString.call(b.fallthrough))return nb(a,b.fallthrough,c,d);for(e=0;e<b.fallthrough.length;e++){var f=nb(a,b.fallthrough[e],c,d);if(f)return f}}}function nf(a){a="string"==typeof a?a:Da[a.keyCode];return"Ctrl"==a||"Alt"==a||"Shift"==a||"Mod"==a}function of(a,b){if(ga&&34==a.keyCode&&a["char"])return!1;var c=Da[a.keyCode],d=c;if(null==d||a.altGraphKey)return!1;a.altKey&&"Alt"!=c&&(d="Alt-"+d);(pf?a.metaKey:a.ctrlKey)&&"Ctrl"!=c&&(d="Ctrl-"+d);(pf?a.ctrlKey:a.metaKey)&&"Cmd"!=c&&(d=
"Cmd-"+d);!b&&a.shiftKey&&"Shift"!=c&&(d="Shift-"+d);return d}function wc(a){return"string"==typeof a?Ob[a]:a}function ob(a,b){for(var c=a.doc.sel.ranges,d=[],e=0;e<c.length;e++){for(var f=b(c[e]);d.length&&0>=x(f.from,B(d).to);){var g=d.pop();if(0>x(g.from,f.from)){f.from=g.from;break}}d.push(f)}Y(a,function(){for(var b=d.length-1;0<=b;b--)lb(a.doc,"",d[b].from,d[b].to,"+delete");eb(a)})}function qf(a,b){var c=r(a.doc,b),d=ja(c);d!=c&&(b=D(d));return Wc(!0,a,d,b,1)}function rf(a,b){var c=qf(a,b.line),
d=r(a.doc,c.line),e=ya(d);return e&&0!=e[0].level?c:(d=Math.max(0,d.text.search(/\S/)),q(c.line,b.line==c.line&&b.ch<=d&&b.ch?0:d,c.sticky))}function xc(a,b,c){if("string"==typeof b&&(b=yc[b],!b))return!1;a.display.input.ensurePolled();var d=a.display.shift,e=!1;try{a.isReadOnly()&&(a.state.suppressEdits=!0),c&&(a.display.shift=!1),e=b(a)!=Cd}finally{a.display.shift=d,a.state.suppressEdits=!1}return e}function xg(a,b,c){for(var d=0;d<a.state.keyMaps.length;d++){var e=nb(b,a.state.keyMaps[d],c,a);
if(e)return e}return a.options.extraKeys&&nb(b,a.options.extraKeys,c,a)||nb(b,a.options.keyMap,c,a)}function zc(a,b,c,d){var e=a.state.keySeq;if(e){if(nf(b))return"handled";yg.set(50,function(){a.state.keySeq==e&&(a.state.keySeq=null,a.display.input.reset())});b=e+" "+b}d=xg(a,b,d);"multi"==d&&(a.state.keySeq=b);"handled"==d&&M(a,"keyHandled",a,b,c);if("handled"==d||"multi"==d)P(c),nd(a);return e&&!d&&/\'$/.test(b)?(P(c),!0):!!d}function sf(a,b){var c=of(b,!0);return c?b.shiftKey&&!a.state.keySeq?
zc(a,"Shift-"+c,b,function(b){return xc(a,b,!0)})||zc(a,c,b,function(b){if("string"==typeof b?/^go[A-Z]/.test(b):b.motion)return xc(a,b)}):zc(a,c,b,function(b){return xc(a,b)}):!1}function zg(a,b,c){return zc(a,"'"+c+"'",b,function(b){return xc(a,b,!0)})}function tf(a){this.curOp.focus=pa();if(!H(this,a)){C&&11>z&&27==a.keyCode&&(a.returnValue=!1);var b=a.keyCode;this.display.shift=16==b||a.shiftKey;var c=sf(this,a);ga&&(Dd=c?b:null,!c&&88==b&&!uf&&(ea?a.metaKey:a.ctrlKey)&&this.replaceSelection("",
null,"cut"));18!=b||/\bCodeMirror-crosshair\b/.test(this.display.lineDiv.className)||Ag(this)}}function Ag(a){function b(a){18!=a.keyCode&&a.altKey||(bb(c,"CodeMirror-crosshair"),da(document,"keyup",b),da(document,"mouseover",b))}var c=a.display.lineDiv;Va(c,"CodeMirror-crosshair");w(document,"keyup",b);w(document,"mouseover",b)}function vf(a){16==a.keyCode&&(this.doc.sel.shift=!1);H(this,a)}function wf(a){if(!(ta(this.display,a)||H(this,a)||a.ctrlKey&&!a.altKey||ea&&a.metaKey)){var b=a.keyCode,c=
a.charCode;if(ga&&b==Dd)Dd=null,P(a);else if(!ga||a.which&&!(10>a.which)||!sf(this,a))if(b=String.fromCharCode(null==c?b:c),"\b"!=b&&!zg(this,a,b))this.display.input.onKeyPress(a)}}function Bg(a){var b=this.display;if(!(H(this,a)||b.activeTouch&&b.input.supportsTouch()))if(b.input.ensurePolled(),b.shift=a.shiftKey,ta(b,a))L||(b.scroller.draggable=!1,setTimeout(function(){return b.scroller.draggable=!0},100));else if(!Ed(this,a,"gutterClick",!0)){var c=Qa(this,a);window.focus();switch($d(a)){case 1:this.state.selectingText?
this.state.selectingText(a):c?Cg(this,a,c):(a.target||a.srcElement)==b.scroller&&P(a);break;case 2:L&&(this.state.lastMiddleDown=+new Date);c&&tc(this.doc,c);setTimeout(function(){return b.input.focus()},20);P(a);break;case 3:Fd?xf(this,a):gg(this)}}}function Cg(a,b,c){C?setTimeout(Gc(Be,a),0):a.curOp.focus=pa();var d=+new Date,e;Ac&&Ac.time>d-400&&0==x(Ac.pos,c)?e="triple":Bc&&Bc.time>d-400&&0==x(Bc.pos,c)?(e="double",Ac={time:d,pos:c}):(e="single",Bc={time:d,pos:c});var d=a.doc.sel,f=ea?b.metaKey:
b.ctrlKey,g;a.options.dragDrop&&Dg&&!a.isReadOnly()&&"single"==e&&-1<(g=d.contains(c))&&(0>x((g=d.ranges[g]).from(),c)||0<c.xRel)&&(0<x(g.to(),c)||0>c.xRel)?Eg(a,b,c,f):Fg(a,b,c,e,f)}function Eg(a,b,c,d){var e=a.display,f=+new Date,g=J(a,function(h){L&&(e.scroller.draggable=!1);a.state.draggingText=!1;da(document,"mouseup",g);da(e.scroller,"drop",g);10>Math.abs(b.clientX-h.clientX)+Math.abs(b.clientY-h.clientY)&&(P(h),!d&&+new Date-200<f&&tc(a.doc,c),L||C&&9==z?setTimeout(function(){document.body.focus();
e.input.focus()},20):e.input.focus())});L&&(e.scroller.draggable=!0);a.state.draggingText=g;g.copy=ea?b.altKey:b.ctrlKey;e.scroller.dragDrop&&e.scroller.dragDrop();w(document,"mouseup",g);w(e.scroller,"drop",g)}function Fg(a,b,c,d,e){function f(b){if(0!=x(y,b))if(y=b,"rect"==d){for(var e=[],f=a.options.tabSize,g=ba(r(l,c.line).text,c.ch,f),h=ba(r(l,b.line).text,b.ch,f),k=Math.min(g,h),g=Math.max(g,h),h=Math.min(c.line,b.line),u=Math.min(a.lastLine(),Math.max(c.line,b.line));h<=u;h++){var v=r(l,h).text,
w=Hc(v,k,f);k==g?e.push(new A(q(h,w),q(h,w))):v.length>w&&e.push(new A(q(h,w),q(h,Hc(v,g,f))))}e.length||e.push(new A(c,c));O(l,ha(p.ranges.slice(0,n).concat(e),n),{origin:"*mouse",scroll:!1});a.scrollIntoView(b)}else k=m,e=k.anchor,f=b,"single"!=d&&(b="double"==d?a.findWordAt(b):new A(q(b.line,0),t(l,q(b.line+1,0))),0<x(b.anchor,e)?(f=b.head,e=dc(k.from(),b.anchor)):(f=b.anchor,e=cc(k.to(),b.head))),b=p.ranges.slice(0),b[n]=new A(t(l,e),f),O(l,ha(b,n),Gd)}function g(b){var c=++B,e=Qa(a,b,!0,"rect"==
d);if(e)if(0!=x(e,y)){a.curOp.focus=pa();f(e);var h=rd(k,l);(e.line>=h.to||e.line<h.from)&&setTimeout(J(a,function(){B==c&&g(b)}),150)}else{var m=b.clientY<z.top?-20:b.clientY>z.bottom?20:0;m&&setTimeout(J(a,function(){B==c&&(k.scroller.scrollTop+=m,g(b))}),50)}}function h(b){a.state.selectingText=!1;B=Infinity;P(b);k.input.focus();da(document,"mousemove",C);da(document,"mouseup",D);l.history.lastSelOrigin=null}var k=a.display,l=a.doc;P(b);var m,n,p=l.sel,u=p.ranges;e&&!b.shiftKey?(n=l.sel.contains(c),
m=-1<n?u[n]:new A(c,c)):(m=l.sel.primary(),n=l.sel.primIndex);if(Gg?b.shiftKey&&b.metaKey:b.altKey)d="rect",e||(m=new A(c,c)),c=Qa(a,b,!0,!0),n=-1;else if("double"==d){var v=a.findWordAt(c);m=a.display.shift||l.extend?Jb(l,m,v.anchor,v.head):v}else"triple"==d?(v=new A(q(c.line,0),t(l,q(c.line+1,0))),m=a.display.shift||l.extend?Jb(l,m,v.anchor,v.head):v):m=Jb(l,m,c);e?-1==n?(n=u.length,O(l,ha(u.concat([m]),n),{scroll:!1,origin:"*mouse"})):1<u.length&&u[n].empty()&&"single"==d&&!b.shiftKey?(O(l,ha(u.slice(0,
n).concat(u.slice(n+1)),0),{scroll:!1,origin:"*mouse"}),p=l.sel):Ad(l,n,m,Gd):(n=0,O(l,new Z([m],0),Gd),p=l.sel);var y=c,z=k.wrapper.getBoundingClientRect(),B=0,C=J(a,function(a){$d(a)?g(a):h(a)}),D=J(a,h);a.state.selectingText=D;w(document,"mousemove",C);w(document,"mouseup",D)}function Ed(a,b,c,d){var e,f;try{e=b.clientX,f=b.clientY}catch(k){return!1}if(e>=Math.floor(a.display.gutters.getBoundingClientRect().right))return!1;d&&P(b);d=a.display;var g=d.lineDiv.getBoundingClientRect();if(f>g.bottom||
!ca(a,c))return Xc(b);f-=g.top-d.viewOffset;for(g=0;g<a.options.gutters.length;++g){var h=d.gutters.childNodes[g];if(h&&h.getBoundingClientRect().right>=e)return e=Ha(a.doc,f),F(a,c,a,e,a.options.gutters[g],b),Xc(b)}}function xf(a,b){var c;(c=ta(a.display,b))||(c=ca(a,"gutterContextMenu")?Ed(a,b,"gutterContextMenu",!1):!1);if(!c&&!H(a,b,"contextmenu"))a.display.input.onContextMenu(b)}function yf(a){a.display.wrapper.className=a.display.wrapper.className.replace(/\s*cm-s-\S+/g,"")+a.options.theme.replace(/(^|\s)\s*/g,
" cm-s-");Cb(a)}function Pb(a){Le(a);Q(a);pd(a)}function Hg(a,b,c){!b!=!(c&&c!=pb)&&(c=a.display.dragFunctions,b=b?w:da,b(a.display.scroller,"dragstart",c.start),b(a.display.scroller,"dragenter",c.enter),b(a.display.scroller,"dragover",c.over),b(a.display.scroller,"dragleave",c.leave),b(a.display.scroller,"drop",c.drop))}function Ig(a){a.options.lineWrapping?(Va(a.display.wrapper,"CodeMirror-wrap"),a.display.sizer.style.minWidth="",a.display.sizerWidth=null):(bb(a.display.wrapper,"CodeMirror-wrap"),
Sc(a));md(a);Q(a);Cb(a);setTimeout(function(){return db(a)},100)}function E(a,b){var c=this;if(!(this instanceof E))return new E(a,b);this.options=b=b?Fa(b):{};Fa(zf,b,!1);vd(b);var d=b.value;"string"==typeof d&&(d=new S(d,b.mode,null,b.lineSeparator));this.doc=d;var e=new E.inputStyles[b.inputStyle](this),e=this.display=new Pf(a,d,e);e.wrapper.CodeMirror=this;Le(this);yf(this);b.lineWrapping&&(this.display.wrapper.className+=" CodeMirror-wrap");He(this);this.state={keyMaps:[],overlays:[],modeGen:0,
overwrite:!1,delayingBlurEvent:!1,focused:!1,suppressEdits:!1,pasteIncoming:!1,cutIncoming:!1,selectingText:!1,draggingText:!1,highlight:new Sa,keySeq:null,specialChars:null};b.autofocus&&!sb&&e.input.focus();C&&11>z&&setTimeout(function(){return c.display.input.reset(!0)},20);Jg(this);Af||(tg(),Af=!0);fb(this);this.curOp.forceUpdate=!0;Pe(this,d);b.autofocus&&!sb||this.hasFocus()?setTimeout(Gc(od,this),20):Eb(this);for(var f i